"""
rmath.array — High-performance N-dimensional array engine and autograd system.

This module provides the core `Array` and `Tensor` classes for parallel numerical 
computing and deep learning. All element-wise operations and matrix math are 
backed by highly optimized Rust kernels (Rayon, faer, matrixmultiply).

Key Features:
    1. Parallel Core: Every element-wise operation (sin, exp, arithmetic) 
       automatically uses the Rayon thread pool for data > 8,192 elements.
    2. Tiered Storage:
       - Inline: Small arrays (<32 elements) use zero-allocation stack storage.
       - Heap: Shared memory via Arc-wrapped contiguous buffers.
       - Mmap: Memory-mapped files for processing datasets larger than RAM.
    3. Autograd Engine: The `Tensor` class provides a dynamic computational 
       graph with automatic differentiation for building neural networks.
    4. Interoperability: Zero-copy conversion to and from NumPy ndarrays.
"""

from typing import List, Sequence, Union, Tuple, Optional, Any, Iterator, Dict
from rmath.vector import Vector

class Array:
    """High-performance N-dimensional array engine for numerical computing.
    
    `Array` supports SIMD-accelerated math kernels, automatic broadcasting,
    and zero-copy interop with NumPy, PyTorch, and JAX.
    """

    def __init__(self, data: Union[Sequence, Vector, float], dtype: Optional[str] = None) -> None: ...

    # --- Constructors (Static Methods) ---
    @staticmethod
    def zeros(*shape: int, dtype: Optional[str] = None) -> "Array": ...
    @staticmethod
    def ones(*shape: int, dtype: Optional[str] = None) -> "Array": ...
    @staticmethod
    def zeros_nd(shape: List[int]) -> "Array": ...
    @staticmethod
    def ones_nd(shape: List[int]) -> "Array": ...
    @staticmethod
    def eye(n: int) -> "Array": ...
    @staticmethod
    def randn(*shape: int) -> "Array": ...
    @staticmethod
    def rand_uniform(*shape: int) -> "Array": ...
    @staticmethod
    def arange(start: float, stop: float, step: float) -> "Array": ...
    @staticmethod
    def range(start: float, stop: float, step: float) -> "Array": ...
    @staticmethod
    def linspace(start: float, stop: float, num: int) -> "Array": ...
    @staticmethod
    def full(*args: Union[int, float]) -> "Array": ...
    @staticmethod
    def from_list(data: Sequence[float], shape: Sequence[int]) -> "Array": ...
    @staticmethod
    def from_numpy(arr: Any) -> "Array": ...
    @staticmethod
    def from_torch(tensor: Any) -> "Array": ...
    @staticmethod
    def from_jax(arr: Any) -> "Array": ...
    @staticmethod
    def from_dataframe(df: Any) -> "Array": ...

    # --- Persistence ---
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> "Array": ...
    def save_bin(self, path: str) -> None: ...
    def save_csv(self, path: str, header: Optional[List[str]] = None) -> None: ...
    @staticmethod
    def load_csv(path: str) -> "Array": ...
    @staticmethod
    def load_csv_with_header(path: str) -> Tuple["Array", List[str]]: ...
    def save_safetensors(self, path: str, key: str) -> None: ...
    @staticmethod
    def load_safetensors(path: str, key: str) -> "Array": ...

    # --- Properties ---
    @property
    def shape(self) -> Tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def dtype(self) -> str: ...
    def nrows(self) -> int: ...
    def ncols(self) -> int: ...

    # --- Protocols ---
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: float) -> None: ...
    def __array__(self, dtype: Any = None, copy: Any = None) -> Any: ...
    def __dlpack__(self, stream: Any = None) -> Any: ...
    def __dlpack_device__(self) -> Tuple[int, int]: ...

    # --- Arithmetic Operators ---
    def __add__(self, other: Any) -> "Array": ...
    def __radd__(self, other: Any) -> "Array": ...
    def __iadd__(self, other: Any) -> None: ...
    def __sub__(self, other: Any) -> "Array": ...
    def __rsub__(self, other: Any) -> "Array": ...
    def __isub__(self, other: Any) -> None: ...
    def __mul__(self, other: Any) -> "Array": ...
    def __rmul__(self, other: Any) -> "Array": ...
    def __imul__(self, other: Any) -> None: ...
    def __truediv__(self, other: Any) -> "Array": ...
    def __rtruediv__(self, other: Any) -> "Array": ...
    def __itruediv__(self, other: Any) -> None: ...
    def __pow__(self, other: Any) -> "Array": ...
    def __neg__(self) -> "Array": ...
    def __abs__(self) -> "Array": ...
    def __matmul__(self, other: Any) -> Any: ...

    # --- Named Arithmetic ---
    def add(self, other: Any) -> "Array": ...
    def sub(self, other: Any) -> "Array": ...
    def mul(self, other: Any) -> "Array": ...
    def div(self, other: Any) -> "Array": ...
    def pow(self, other: Any) -> "Array": ...
    def add_array(self, other: "Array") -> "Array": ...
    def sub_array(self, other: "Array") -> "Array": ...
    def mul_array_elementwise(self, other: "Array") -> "Array": ...
    def div_array_elementwise(self, other: "Array") -> "Array": ...
    def matmul(self, other: Any) -> Any: ...
    def matmul_trans(self, other: Vector) -> Vector: ...

    # --- Comparison ---
    def gt(self, val: float) -> List[bool]: ...
    def lt(self, val: float) -> List[bool]: ...
    def ge(self, val: float) -> List[bool]: ...
    def le(self, val: float) -> List[bool]: ...
    def eq_scalar(self, val: float) -> List[bool]: ...
    def ne_scalar(self, val: float) -> List[bool]: ...
    def isnan(self) -> List[bool]: ...
    def isfinite(self) -> List[bool]: ...
    def isinf(self) -> List[bool]: ...
    def where_scalar(self, mask: List[bool], other: float) -> "Array": ...

    # --- Shape & Layout ---
    def reshape(self, shape: List[int]) -> "Array": ...
    def flatten(self) -> "Array": ...
    def squeeze(self) -> "Array": ...
    def expand_dims(self, axis: int) -> "Array": ...
    def transpose(self) -> "Array": ...
    @property
    def t(self) -> "Array": ...
    def slice_rows(self, start: int, end: int) -> "Array": ...
    def get_row(self, i: int) -> List[float]: ...
    def get_col(self, j: int) -> List[float]: ...
    def copy(self) -> "Array": ...
    def pad(self, top: int, bottom: int, left: int, right: int, val: float = 0.0) -> "Array": ...

    # --- Linear Algebra ---
    def inv(self) -> "Array": ...
    def det(self) -> float: ...
    def solve(self, b: "Array") -> "Array": ...
    def trace(self) -> float: ...
    def rank(self) -> int: ...
    def qr(self) -> Tuple["Array", "Array"]: ...
    def svd(self) -> Tuple["Array", Vector, "Array"]: ...
    def eigh(self) -> Tuple[Vector, "Array"]: ...
    def cholesky(self) -> "Array": ...
    def pseudo_inv(self) -> "Array": ...
    def gram_matrix(self) -> "Array": ...
    def norm_frobenius(self) -> float: ...

    # --- Geometry & Stats ---
    def distance(self, other: "Array") -> float: ...
    def cdist(self, other: "Array") -> "Array": ...
    def normalize(self, mean: Any, std: Any) -> "Array": ...
    def correlation_matrix(self) -> "Array": ...
    def covariance(self) -> "Array": ...

    # --- Reductions ---
    def sum(self, axis: Optional[int] = None) -> Any: ...
    def sum_all(self) -> float: ...
    def mean(self, axis: Optional[int] = None) -> Any: ...
    def mean_axis0(self) -> Vector: ...
    def mean_axis1(self) -> Vector: ...
    def variance(self, axis: Optional[int] = None) -> Any: ...
    def var_axis0(self) -> Vector: ...
    def std_dev(self, axis: Optional[int] = None) -> Any: ...
    def std_axis0(self) -> Vector: ...
    def min(self) -> float: ...
    def max(self) -> float: ...
    def argmin(self) -> int: ...
    def argmax(self) -> int: ...
    def prod(self) -> float: ...

    # --- Math ---
    def abs(self) -> "Array": ...
    def sqrt(self) -> "Array": ...
    def cbrt(self) -> "Array": ...
    def exp(self) -> "Array": ...
    def exp2(self) -> "Array": ...
    def expm1(self) -> "Array": ...
    def log(self) -> "Array": ...
    def log2(self) -> "Array": ...
    def log10(self) -> "Array": ...
    def log1p(self) -> "Array": ...
    def sin(self) -> "Array": ...
    def cos(self) -> "Array": ...
    def tan(self) -> "Array": ...
    def asin(self) -> "Array": ...
    def acos(self) -> "Array": ...
    def atan(self) -> "Array": ...
    def sinh(self) -> "Array": ...
    def cosh(self) -> "Array": ...
    def tanh(self) -> "Array": ...
    def ceil(self) -> "Array": ...
    def floor(self) -> "Array": ...
    def round(self) -> "Array": ...
    def trunc(self) -> "Array": ...
    def fract(self) -> "Array": ...
    def signum(self) -> "Array": ...
    def recip(self) -> "Array": ...
    def pow_scalar(self, p: float) -> "Array": ...
    def clamp(self, lo: float, hi: float) -> "Array": ...
    def atan2_scalar(self, other: float) -> "Array": ...
    def lerp_scalar(self, other: float, t: float) -> "Array": ...
    def fma(self, mul: float, add: float) -> "Array": ...

    # --- Machine Learning / NN ---
    def sigmoid(self) -> "Array": ...
    def sigmoid_deriv(self) -> "Array": ...
    def relu(self) -> "Array": ...
    def relu_deriv(self) -> "Array": ...
    def leaky_relu(self, alpha: float) -> "Array": ...
    def leaky_relu_deriv(self, alpha: float) -> "Array": ...
    def elu(self, alpha: float) -> "Array": ...
    def selu(self) -> "Array": ...
    def gelu(self) -> "Array": ...
    def swish(self) -> "Array": ...
    def mish(self) -> "Array": ...
    def softplus(self) -> "Array": ...
    def softmax(self) -> "Array": ...
    def log_softmax(self) -> "Array": ...
    def hardswish(self) -> "Array": ...
    def mse_loss(self, target: "Array") -> float: ...
    def mae_loss(self, target: "Array") -> float: ...
    def binary_cross_entropy(self, target: "Array") -> float: ...
    def cross_entropy_loss(self, labels: List[int]) -> float: ...
    def batch_norm(self, mu: Vector, sigma: Vector, gamma: Vector, beta: Vector) -> "Array": ...
    def layer_norm(self, eps: float) -> "Array": ...
    def dropout(self, p: float) -> "Array": ...
    def max_pool2d(self, kernel_size: int) -> "Array": ...
    def avg_pool2d(self, kernel_size: int) -> "Array": ...
    def mse_grad(self, target: "Array") -> "Array": ...
    def softmax_ce_grad(self, labels: List[int]) -> "Array": ...

    # --- Interop ---
    def to_list(self) -> List[List[float]]: ...
    def to_numpy(self) -> Any: ...
    def to_torch(self) -> Any: ...
    def to_jax(self) -> Any: ...
    def to_dataframe(self, columns: Optional[List[str]] = None) -> Any: ...
    def to_series(self, name: Optional[str] = None) -> Any: ...
    def to_flat_py(self) -> List[float]: ...
    def to_flat_list(self) -> List[float]: ...
    def tolist(self) -> List[List[float]]: ...
    def lazy(self) -> "LazyArray": ...
    def sklearn_shape(self) -> Tuple[int, int]: ...
    def validate_sklearn(self) -> None: ...
    def memory_bytes(self) -> int: ...
    def estimated_bytes(self) -> int: ...

class Tensor:
    """Array wrapper with Autograd support for deep learning."""

    def __init__(self, data: Any, requires_grad: bool = False, dtype: Optional[str] = None) -> None: ...
    
    @staticmethod
    def from_array(arr: Array, requires_grad: bool = False) -> "Tensor": ...

    @property
    def data(self) -> Array: ...
    @property
    def grad(self) -> Optional[Array]: ...
    @grad.setter
    def grad(self, value: Optional[Array]) -> None: ...
    @property
    def shape(self) -> Tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def dtype(self) -> str: ...
    @property
    def requires_grad(self) -> bool: ...
    @requires_grad.setter
    def requires_grad(self, value: bool) -> None: ...
    
    def backward(self) -> None: ...
    def zero_grad(self) -> None: ...
    def build_topo(self) -> List["Tensor"]: ...
    def requires_grad_(self, requires_grad: bool) -> "Tensor": ...
    def update_data(self, new_data: Array) -> None: ...

    def __repr__(self) -> str: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __add__(self, other: Any) -> "Tensor": ...
    def __radd__(self, other: Any) -> "Tensor": ...
    def __sub__(self, other: Any) -> "Tensor": ...
    def __rsub__(self, other: Any) -> "Tensor": ...
    def __mul__(self, other: Any) -> "Tensor": ...
    def __rmul__(self, other: Any) -> "Tensor": ...
    def __truediv__(self, other: Any) -> "Tensor": ...
    def __rtruediv__(self, other: Any) -> "Tensor": ...
    def __matmul__(self, other: "Tensor") -> "Tensor": ...
    def __rmatmul__(self, other: "Tensor") -> "Tensor": ...
    def __neg__(self) -> "Tensor": ...
    def abs(self) -> "Tensor": ...
    def exp(self) -> "Tensor": ...
    def log(self) -> "Tensor": ...
    def tanh(self) -> "Tensor": ...
    def sigmoid(self) -> "Tensor": ...
    def relu(self) -> "Tensor": ...
    def sum(self) -> "Tensor": ...
    def mean(self) -> "Tensor": ...
    def reshape(self, shape: List[int]) -> "Tensor": ...
    def transpose(self) -> "Tensor": ...
    @property
    def t(self) -> "Tensor": ...

    @staticmethod
    def zeros(*shape: int, requires_grad: bool = False, **kwargs: Any) -> "Tensor": ...
    @staticmethod
    def ones(*shape: int, requires_grad: bool = False, **kwargs: Any) -> "Tensor": ...
    @staticmethod
    def randn(*shape: int, requires_grad: bool = False, **kwargs: Any) -> "Tensor": ...

class SGD:
    """Stochastic Gradient Descent optimizer."""
    def __init__(self, params: List[Tensor], lr: float, momentum: float = 0.0) -> None: ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...

class Adam:
    """Adam optimizer."""
    def __init__(self, params: List[Tensor], lr: float = 0.001, beta1: float = 0.9, beta2: float = 0.999, eps: float = 1e-8) -> None: ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...

class LazyArray:
    """Deferred execution pipeline for fused array operations."""
    @staticmethod
    def open(path: str) -> "LazyArray": ...
    @staticmethod
    def open_bin(path: str, rows: int, cols: int) -> "LazyArray": ...
    def peek(self) -> List[int]: ...
    def sin(self) -> "LazyArray": ...
    def cos(self) -> "LazyArray": ...
    def exp(self) -> "LazyArray": ...
    def sigmoid(self) -> "LazyArray": ...
    def add(self, val: float) -> "LazyArray": ...
    def mul(self, val: float) -> "LazyArray": ...
    def abs(self) -> "LazyArray": ...
    def pow(self, val: float) -> "LazyArray": ...
    def execute(self) -> Array: ...
    def load(self) -> Array: ...
    def load_rows(self, start: int, end: int) -> Array: ...
    def chunks(self, chunk_size: int) -> Iterator[Array]: ...
    def sum(self) -> float: ...

class ChunkIterator:
    def __iter__(self) -> "ChunkIterator": ...
    def __next__(self) -> Optional[Array]: ...

class MmapArray:
    """Memory-mapped array for processing datasets larger than RAM."""
    @staticmethod
    def mmap(path: str, rows: int, cols: int) -> "MmapArray": ...
    @property
    def shape(self) -> Tuple[int, int]: ...
    def load_all(self) -> Array: ...
    def get_element(self, r: int, c: int) -> float: ...
    def chunks(self, chunk_size: int) -> Iterator[Array]: ...

class MmapChunkIterator:
    def __iter__(self) -> "MmapChunkIterator": ...
    def __next__(self) -> Optional[Array]: ...

# Functional API
def arange(start: float, stop: float, step: float) -> Array: ...
def zeros(rows: int, cols: int) -> Array: ...
def ones(rows: int, cols: int) -> Array: ...
def randn(*shape: int) -> Array: ...
def rand_uniform(*shape: int) -> Array: ...

# Submodules
linalg: Any
nn: Any
