"""
rmath.array — parallel 2-D Array class + functional wrappers.
Row-major `Vec<Vec<f64>>` backed, all element-wise ops run on Rayon.
Designed for data science, ML preprocessing, and numerical analysis.
Maintain this file: stubs/rmath/array.pyi
"""

from typing import List, Sequence, Union, Tuple
from rmath.vector import Vector

class Array:
    """High-performance N-dimensional array engine for numerical computing.
    
    `Array` provides SIMD-accelerated math kernels, automatic broadcasting,
    and zero-copy interop with NumPy.
    
    Storage Tiers:
    - Inline (<32 elements): Stack-allocated, zero-allocation math.
    - Heap: Shared Arc memory for large datasets.
    - Mmap: Lazy-loaded files for GB-scale processing.
    """

    def __init__(self, data: Union[Sequence, Vector, float]) -> None:
        """Create a new Array from nested sequences, a Vector, or a scalar.
        
        Example:
            >>> rm.Array([[1, 2], [3, 4]])
            >>> rm.Array([1, 2, 3])
        """

    # --- Constructors ---
    @staticmethod
    def zeros(*shape: int) -> "Array": ...
    @staticmethod
    def ones(*shape: int) -> "Array": ...
    @staticmethod
    def eye(n: int) -> "Array": ...
    @staticmethod
    def randn(*shape: int) -> "Array": ...
    @staticmethod
    def rand_uniform(*shape: int) -> "Array": ...
    @staticmethod
    def arange(start: float, stop: float, step: float) -> "Array": ...
    @staticmethod
    def linspace(start: float, stop: float, num: int) -> "Array": ...
    @staticmethod
    def full(*args: Union[int, float]) -> "Array":
        """Create an array of given shape filled with a value.
        Usage: rm.Array.full(rows, cols, ..., value)
        """
    @staticmethod
    def from_flat(data: Sequence[float], shape: Sequence[int]) -> "Array": ...
    @staticmethod
    def from_list(data: Sequence[float], shape: Sequence[int]) -> "Array": ...

    # --- Protocol ---
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...   # number of rows

    # --- Operators (scalar OR Array dispatch) ---
    def __add__(self, other: Union[float, "Array"]) -> "Array": ...
    def __radd__(self, other: float) -> "Array": ...
    def __sub__(self, other: Union[float, "Array"]) -> "Array": ...
    def __rsub__(self, other: float) -> "Array": ...
    def __mul__(self, other: Union[float, "Array"]) -> "Array": ...
    def __rmul__(self, other: float) -> "Array": ...
    def __truediv__(self, other: Union[float, "Array"]) -> "Array": ...
    def __neg__(self) -> "Array": ...
    def __matmul__(self, other: "Array") -> "Array": ...  # matrix multiply

    # --- Shape & metadata ---
    def shape(self) -> Tuple[int, ...]: ...
    def size(self) -> int: ...
    def nrows(self) -> int: ...
    def ncols(self) -> int: ...

    # --- Data access ---
    def to_list(self) -> List[List[float]]: ...
    def flatten(self) -> List[float]: ...
    def row(self, i: int) -> List[float]: ...           # raises IndexError
    def col(self, j: int) -> List[float]: ...           # raises IndexError
    def get(self, i: int, j: int) -> float: ...         # raises IndexError
    def diag_extract(self) -> List[float]: ...          # square only
    def triu(self) -> "Array": ...
    def tril(self) -> "Array": ...
    def reshape(self, rows: int, cols: int) -> "Array": ...  # raises ValueError

    # --- Scalar broadcast ---
    def add_scalar(self, s: float) -> "Array": ...
    def sub_scalar(self, s: float) -> "Array": ...
    def mul_scalar(self, s: float) -> "Array": ...
    def div_scalar(self, s: float) -> "Array": ...      # raises ZeroDivisionError
    def pow_scalar(self, exp: float) -> "Array": ...
    def clamp(self, lo: float, hi: float) -> "Array": ...

    # --- Array-Array element-wise ---
    def add_array(self, other: "Array") -> "Array": ...
    def sub_array(self, other: "Array") -> "Array": ...
    def mul_array(self, other: "Array") -> "Array": ...
    def div_array(self, other: "Array") -> "Array": ...  # raises ZeroDivisionError

    # --- Matrix operations ---
    def transpose(self) -> "Array": ...
    def matmul(self, other: "Array") -> "Array": ...
    def trace(self) -> float: ...                        # square only
    def det(self) -> float: ...                          # square only
    def inv(self) -> "Array": ...                        # square + non-singular
    def solve(self, b: Sequence[float]) -> List[float]: ...  # square + non-singular

    # --- Element-wise math ---
    def abs(self) -> "Array": ...
    def sqrt(self) -> "Array": ...
    def cbrt(self) -> "Array": ...
    def ceil(self) -> "Array": ...
    def floor(self) -> "Array": ...
    def round(self) -> "Array": ...
    def trunc(self) -> "Array": ...
    def sin(self) -> "Array": ...
    def cos(self) -> "Array": ...
    def tan(self) -> "Array": ...
    def asin(self) -> "Array": ...
    def acos(self) -> "Array": ...
    def atan(self) -> "Array": ...
    def sinh(self) -> "Array": ...
    def cosh(self) -> "Array": ...
    def tanh(self) -> "Array": ...
    def exp(self) -> "Array": ...
    def exp2(self) -> "Array": ...
    def expm1(self) -> "Array": ...
    def log(self) -> "Array": ...
    def log2(self) -> "Array": ...
    def log10(self) -> "Array": ...
    def log1p(self) -> "Array": ...

    # --- ML activations ---
    def sigmoid(self) -> "Array": ...
    def relu(self) -> "Array": ...
    def leaky_relu(self, alpha: float) -> "Array": ...
    def softmax(self) -> "Array": ...       # row-wise, numerically stable

    # --- Normalization (ML preprocessing) ---
    def normalize(self) -> "Array": ...         # global [0, 1]
    def col_normalize(self) -> "Array": ...     # per-column [0, 1]  (MinMaxScaler)
    def z_normalize(self) -> "Array": ...       # global z-score
    def col_z_normalize(self) -> "Array": ...   # per-column z-score (StandardScaler)

    # --- Global reductions ---
    def sum(self) -> float: ...
    def prod(self) -> float: ...
    def mean(self) -> float: ...
    def variance(self) -> float: ...
    def std_dev(self) -> float: ...
    def min(self) -> float: ...
    def max(self) -> float: ...

    # --- Per-axis reductions ---
    def row_sums(self) -> List[float]: ...
    def col_sums(self) -> List[float]: ...
    def row_means(self) -> List[float]: ...
    def col_means(self) -> List[float]: ...
    def row_min(self) -> List[float]: ...
    def row_max(self) -> List[float]: ...
    def col_min(self) -> List[float]: ...
    def col_max(self) -> List[float]: ...
    def row_variance(self) -> List[float]: ...
    def col_variance(self) -> List[float]: ...
    def row_std_dev(self) -> List[float]: ...
    def col_std_dev(self) -> List[float]: ...

    # --- Cumulative (row-wise) ---
    def cumsum(self) -> "Array": ...
    def cumprod(self) -> "Array": ...

    # --- Matrix statistics ---
    def covariance_matrix(self) -> "Array": ...      # n>=2 rows required
    def correlation_matrix(self) -> "Array": ...

    # --- Norms ---
    def norm_fro(self) -> float: ...    # Frobenius
    def norm_l1(self) -> float: ...     # sum of abs
    def norm_inf(self) -> float: ...    # max abs

    # --- Predicates ---
    def isnan(self) -> List[List[bool]]: ...
    def isfinite(self) -> List[List[bool]]: ...
    def isinf(self) -> List[List[bool]]: ...
    def any_nan(self) -> bool: ...
    def all_finite(self) -> bool: ...
    def squeeze(self) -> "Array": ...
    def expand_dims(self, axis: int) -> "Array": ...
    def is_prime(self) -> List[bool]: ...
    def into_vector(self) -> Vector: ...
    def copy(self) -> "Array": ...
    def tolist(self) -> List[List[float]]: ...


# ── Functional API (rmath.array.*) ───────────────────────────────────────────

def zeros(rows: int, cols: int) -> Array:
    """Create a new Array of zeros with given rows and columns."""
    ...

def ones(rows: int, cols: int) -> Array:
    """Create a new Array of ones with given rows and columns."""
    ...

def arange(start: float, stop: float, step: float) -> Array:
    """Create a new Array with a range of values (equivalent to `range`)."""
    ...

def range(start: float, stop: float, step: float) -> Array:
    """Create a new Array with a range of values (equivalent to `arange`)."""
    ...

def eye(n: int) -> Array:
    """Create an n x n identity matrix."""
    ...

def full(rows: int, cols: int, value: float) -> Array:
    """Create a new Array filled with a specific value."""
    ...

def diag(values: List[float]) -> Array:
    """Create a diagonal matrix from a list of values."""
    ...

def transpose(a: Array) -> Array:
    """Return the transpose of the given Array."""
    ...

def matmul(a: Array, b: Array) -> Array:
    """Perform matrix multiplication (dot product) between two Arrays."""
    ...

def solve(a: Array, b: Sequence[float]) -> List[float]:
    """
    Solve a linear system Ax = B.
    'a' must be a square, non-singular Array.
    'b' can be a Sequence of floats.
    """
    ...

def inv(a: Array) -> Array:
    """Compute the inverse of a square matrix."""
    ...

def mean(a: Array) -> float:
    """Calculate the global arithmetic mean of an Array."""
    ...

def variance(a: Array) -> float:
    """Calculate the global sample variance of an Array."""
    ...

def std_dev(a: Array) -> float:
    """Calculate the global sample standard deviation of an Array."""
    ...

def sum(a: Array) -> float:
    """Calculate the global sum of all elements in the Array."""
    ...
