"""
rmath.array — High-performance N-dimensional array engine and autograd system.

This module provides the core `Array` and `Tensor` classes for parallel numerical 
computing and deep learning. All element-wise operations and matrix math are 
backed by highly optimized Rust kernels (Rayon, faer, matrixmultiply).

Key Features:
    1. Parallel Core: Every element-wise operation (sin, exp, arithmetic) 
       automatically uses the Rayon thread pool for data > 8,192 elements.
    2. Tiered Storage:
       - Inline: Small arrays (<32 elements) use zero-allocation stack storage.
       - Heap: Shared memory via Arc-wrapped contiguous buffers.
       - Mmap: Memory-mapped files for processing datasets larger than RAM.
    3. Autograd Engine: The `Tensor` class provides a dynamic computational 
       graph with automatic differentiation for building neural networks.
    4. Interoperability: Zero-copy conversion to and from NumPy ndarrays.
"""

from typing import List, Sequence, Union, Tuple, Optional, Any, Iterator, Dict
from rmath.vector import Vector

class Array:
    """High-performance N-dimensional array engine for numerical computing.
    
    `Array` supports SIMD-accelerated math kernels, automatic broadcasting,
    and zero-copy interop with NumPy, PyTorch, and JAX.
    """

    def __init__(self, data: Union[Sequence, Vector, float], dtype: Optional[str] = None) -> None:
        """Create an Array from a nested list, Vector, or scalar."""
        ...

    # --- Constructors (Static Methods) ---
    @staticmethod
    def zeros(*shape: int, dtype: Optional[str] = None) -> "Array":
        """Create an Array filled with zeros."""
        ...
    @staticmethod
    def ones(*shape: int, dtype: Optional[str] = None) -> "Array":
        """Create an Array filled with ones."""
        ...
    @staticmethod
    def zeros_nd(shape: List[int]) -> "Array":
        """Create a zero-filled Array from a shape list."""
        ...
    @staticmethod
    def ones_nd(shape: List[int]) -> "Array":
        """Create a ones-filled Array from a shape list."""
        ...
    @staticmethod
    def eye(n: int) -> "Array":
        """Create an ``n × n`` identity matrix."""
        ...
    @staticmethod
    def randn(*shape: int) -> "Array":
        """Create an Array with standard normal random values."""
        ...
    @staticmethod
    def rand_uniform(*shape: int) -> "Array":
        """Create an Array with uniform random values in [0, 1)."""
        ...
    @staticmethod
    def arange(start: float, stop: float, step: float) -> "Array":
        """Create a 1D Array from ``start`` to ``stop`` by ``step``."""
        ...
    @staticmethod
    def range(start: float, stop: float, step: float) -> "Array":
        """Alias for ``arange``."""
        ...
    @staticmethod
    def linspace(start: float, stop: float, num: int) -> "Array":
        """Create a 1D Array with ``num`` evenly spaced values."""
        ...
    @staticmethod
    def full(*args: Union[int, float]) -> "Array":
        """Create an Array filled with a constant. Last arg is the fill value."""
        ...
    @staticmethod
    def from_list(data: Sequence[float], shape: Sequence[int]) -> "Array":
        """Create an Array from a flat list and a shape."""
        ...
    @staticmethod
    def from_numpy(arr: Any) -> "Array":
        """Create an Array from a NumPy ndarray (copies data)."""
        ...
    @staticmethod
    def from_torch(tensor: Any) -> "Array":
        """Create an Array from a PyTorch tensor."""
        ...
    @staticmethod
    def from_jax(arr: Any) -> "Array":
        """Create an Array from a JAX array."""
        ...
    @staticmethod
    def from_dataframe(df: Any) -> "Array":
        """Create an Array from a pandas DataFrame."""
        ...

    # --- Persistence ---
    def save(self, path: str) -> None:
        """Save to a binary file."""
        ...
    @staticmethod
    def load(path: str) -> "Array":
        """Load from a binary file."""
        ...
    def save_bin(self, path: str) -> None:
        """Save raw binary data."""
        ...
    def save_csv(self, path: str, header: Optional[List[str]] = None) -> None:
        """Save as CSV with optional column headers."""
        ...
    @staticmethod
    def load_csv(path: str) -> "Array":
        """Load from a CSV file."""
        ...
    @staticmethod
    def load_csv_with_header(path: str) -> Tuple["Array", List[str]]:
        """Load CSV returning ``(Array, column_names)``."""
        ...
    def save_safetensors(self, path: str, key: str) -> None:
        """Save in SafeTensors format."""
        ...
    @staticmethod
    def load_safetensors(path: str, key: str) -> "Array":
        """Load from SafeTensors format."""
        ...

    # --- Properties ---
    @property
    def shape(self) -> Tuple[int, ...]:
        """Shape of the array as a tuple."""
        ...
    @property
    def ndim(self) -> int:
        """Number of dimensions."""
        ...
    @property
    def size(self) -> int:
        """Total number of elements."""
        ...
    @property
    def dtype(self) -> str:
        """Data type string (e.g. ``'f64'``)."""
        ...
    def nrows(self) -> int:
        """Number of rows."""
        ...
    def ncols(self) -> int:
        """Number of columns."""
        ...

    # --- Protocols ---
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: float) -> None: ...
    def __array__(self, dtype: Any = None, copy: Any = None) -> Any: ...
    def __dlpack__(self, stream: Any = None) -> Any: ...
    def __dlpack_device__(self) -> Tuple[int, int]: ...

    # --- Arithmetic Operators ---
    def __add__(self, other: Any) -> "Array": ...
    def __radd__(self, other: Any) -> "Array": ...
    def __iadd__(self, other: Any) -> None: ...
    def __sub__(self, other: Any) -> "Array": ...
    def __rsub__(self, other: Any) -> "Array": ...
    def __isub__(self, other: Any) -> None: ...
    def __mul__(self, other: Any) -> "Array": ...
    def __rmul__(self, other: Any) -> "Array": ...
    def __imul__(self, other: Any) -> None: ...
    def __truediv__(self, other: Any) -> "Array": ...
    def __rtruediv__(self, other: Any) -> "Array": ...
    def __itruediv__(self, other: Any) -> None: ...
    def __pow__(self, other: Any) -> "Array": ...
    def __neg__(self) -> "Array": ...
    def __abs__(self) -> "Array": ...
    def __matmul__(self, other: Any) -> Any: ...

    # --- Named Arithmetic ---
    def add(self, other: Any) -> "Array":
        """Element-wise addition."""
        ...
    def sub(self, other: Any) -> "Array":
        """Element-wise subtraction."""
        ...
    def mul(self, other: Any) -> "Array":
        """Element-wise multiplication."""
        ...
    def div(self, other: Any) -> "Array":
        """Element-wise division."""
        ...
    def pow(self, other: Any) -> "Array":
        """Element-wise exponentiation."""
        ...
    def add_array(self, other: "Array") -> "Array":
        """Element-wise addition with another Array."""
        ...
    def sub_array(self, other: "Array") -> "Array":
        """Element-wise subtraction with another Array."""
        ...
    def mul_array_elementwise(self, other: "Array") -> "Array":
        """Hadamard (element-wise) product with another Array."""
        ...
    def div_array_elementwise(self, other: "Array") -> "Array":
        """Element-wise division by another Array."""
        ...
    def matmul(self, other: Any) -> Any:
        """Matrix multiplication."""
        ...
    def matmul_trans(self, other: Vector) -> Vector:
        """Multiply this matrix by a Vector (treated as column vector)."""
        ...

    # --- Comparison ---
    def gt(self, val: float) -> List[bool]:
        """Element-wise greater-than check."""
        ...
    def lt(self, val: float) -> List[bool]:
        """Element-wise less-than check."""
        ...
    def ge(self, val: float) -> List[bool]:
        """Element-wise greater-or-equal check."""
        ...
    def le(self, val: float) -> List[bool]:
        """Element-wise less-or-equal check."""
        ...
    def eq_scalar(self, val: float) -> List[bool]:
        """Element-wise equality check."""
        ...
    def ne_scalar(self, val: float) -> List[bool]:
        """Element-wise inequality check."""
        ...
    def isnan(self) -> List[bool]:
        """Element-wise NaN check."""
        ...
    def isfinite(self) -> List[bool]:
        """Element-wise finiteness check."""
        ...
    def isinf(self) -> List[bool]:
        """Element-wise infinity check."""
        ...
    def where_scalar(self, mask: List[bool], other: float) -> "Array":
        """Select from ``self`` where mask is True, ``other`` where False."""
        ...

    # --- Shape & Layout ---
    def reshape(self, shape: List[int]) -> "Array":
        """Reshape without copying data (total size must match)."""
        ...
    def flatten(self) -> "Array":
        """Flatten to a 1D Array."""
        ...
    def squeeze(self) -> "Array":
        """Remove dimensions of size 1."""
        ...
    def expand_dims(self, axis: int) -> "Array":
        """Insert a new dimension of size 1 at ``axis``."""
        ...
    def transpose(self) -> "Array":
        """Transpose the matrix (swap rows and columns)."""
        ...
    @property
    def t(self) -> "Array":
        """Shorthand for ``transpose()``."""
        ...
    def slice_rows(self, start: int, end: int) -> "Array":
        """Return rows ``[start, end)``."""
        ...
    def get_row(self, i: int) -> List[float]:
        """Return row ``i`` as a Python list."""
        ...
    def get_col(self, j: int) -> List[float]:
        """Return column ``j`` as a Python list."""
        ...
    def copy(self) -> "Array":
        """Return a deep copy."""
        ...
    def pad(self, top: int, bottom: int, left: int, right: int, val: float = 0.0) -> "Array":
        """Pad the array with ``val`` on each side."""
        ...

    # --- Linear Algebra ---
    def is_symmetric(self) -> bool:
        """Check if a 2D array is symmetric (A = A^T)."""
        ...
    def is_positive_definite(self) -> bool:
        """Check if a 2D array is positive definite via Cholesky decomposition."""
        ...
    def inv(self) -> "Array":
        """Compute the matrix inverse."""
        ...
    def det(self) -> float:
        """Compute the determinant."""
        ...
    def solve(self, b: "Array") -> "Array":
        """Solve ``Ax = b`` for ``x``."""
        ...
    def trace(self) -> float:
        """Sum of diagonal elements."""
        ...
    def rank(self) -> int:
        """Numerical rank of the matrix."""
        ...
    def qr(self) -> Tuple["Array", "Array"]:
        """QR decomposition, returns ``(Q, R)``."""
        ...
    def svd(self) -> Tuple["Array", Vector, "Array"]:
        """Singular Value Decomposition, returns ``(U, S, Vt)``."""
        ...
    def eigh(self) -> Tuple[Vector, "Array"]:
        """Eigenvalues and eigenvectors of a symmetric matrix."""
        ...
    def cholesky(self) -> "Array":
        """Cholesky decomposition of a positive-definite matrix."""
        ...
    def pseudo_inv(self) -> "Array":
        """Moore-Penrose pseudo-inverse."""
        ...
    def gram_matrix(self) -> "Array":
        """Gram matrix: ``A^T @ A``."""
        ...
    def norm_frobenius(self) -> float:
        """Frobenius norm: ``sqrt(sum(x²))``."""
        ...

    # --- Geometry & Stats ---
    def distance(self, other: "Array") -> float:
        """Euclidean distance between two arrays."""
        ...
    def cdist(self, other: "Array") -> "Array":
        """Pairwise distance matrix between rows of two arrays."""
        ...
    def normalize(self, mean: Any, std: Any) -> "Array":
        """Z-score normalization: ``(self - mean) / std``."""
        ...
    def correlation_matrix(self) -> "Array":
        """Pearson correlation matrix (rows = variables)."""
        ...
    def covariance(self) -> "Array":
        """Covariance matrix (rows = variables)."""
        ...

    # --- Reductions ---
    def sum(self, axis: Optional[int] = None) -> Any:
        """Sum elements. Pass ``axis`` to reduce along a dimension."""
        ...
    def sum_all(self) -> float:
        """Sum all elements to a scalar."""
        ...
    def mean(self, axis: Optional[int] = None) -> Any:
        """Mean of elements. Pass ``axis`` to reduce along a dimension."""
        ...
    def mean_axis0(self) -> Vector:
        """Column-wise mean (reduce rows)."""
        ...
    def mean_axis1(self) -> Vector:
        """Row-wise mean (reduce columns)."""
        ...
    def variance(self, axis: Optional[int] = None) -> Any:
        """Sample variance. Pass ``axis`` to reduce along a dimension."""
        ...
    def var_axis0(self) -> Vector:
        """Column-wise sample variance."""
        ...
    def std_dev(self, axis: Optional[int] = None) -> Any:
        """Sample standard deviation."""
        ...
    def std_axis0(self) -> Vector:
        """Column-wise standard deviation."""
        ...
    def min(self) -> float:
        """Global minimum element."""
        ...
    def max(self) -> float:
        """Global maximum element."""
        ...
    def argmin(self) -> int:
        """Flat index of the minimum element."""
        ...
    def argmax(self) -> int:
        """Flat index of the maximum element."""
        ...
    def prod(self) -> float:
        """Product of all elements."""
        ...

    # --- Math ---
    def abs(self) -> "Array":
        """Element-wise absolute value."""
        ...
    def sqrt(self) -> "Array":
        """Element-wise square root."""
        ...
    def cbrt(self) -> "Array":
        """Element-wise cube root."""
        ...
    def exp(self) -> "Array":
        """Element-wise ``e^x``."""
        ...
    def exp2(self) -> "Array":
        """Element-wise ``2^x``."""
        ...
    def expm1(self) -> "Array":
        """Element-wise ``e^x - 1``, accurate for small x."""
        ...
    def log(self) -> "Array":
        """Element-wise natural logarithm."""
        ...
    def log2(self) -> "Array":
        """Element-wise base-2 logarithm."""
        ...
    def log10(self) -> "Array":
        """Element-wise base-10 logarithm."""
        ...
    def log1p(self) -> "Array":
        """Element-wise ``ln(1+x)``, accurate for small x."""
        ...
    def sin(self) -> "Array":
        """Element-wise sine."""
        ...
    def cos(self) -> "Array":
        """Element-wise cosine."""
        ...
    def tan(self) -> "Array":
        """Element-wise tangent."""
        ...
    def asin(self) -> "Array":
        """Element-wise arcsine."""
        ...
    def acos(self) -> "Array":
        """Element-wise arccosine."""
        ...
    def atan(self) -> "Array":
        """Element-wise arctangent."""
        ...
    def sinh(self) -> "Array":
        """Element-wise hyperbolic sine."""
        ...
    def cosh(self) -> "Array":
        """Element-wise hyperbolic cosine."""
        ...
    def tanh(self) -> "Array":
        """Element-wise hyperbolic tangent."""
        ...
    def ceil(self) -> "Array":
        """Round each element up."""
        ...
    def floor(self) -> "Array":
        """Round each element down."""
        ...
    def round(self) -> "Array":
        """Round each element to nearest integer."""
        ...
    def trunc(self) -> "Array":
        """Truncate each element toward zero."""
        ...
    def fract(self) -> "Array":
        """Fractional part of each element."""
        ...
    def signum(self) -> "Array":
        """Element-wise sign: ``-1.0``, ``0.0``, or ``1.0``."""
        ...
    def recip(self) -> "Array":
        """Element-wise reciprocal: ``1/x``."""
        ...
    def pow_scalar(self, p: float) -> "Array":
        """Raise every element to the power ``p``."""
        ...
    def clamp(self, lo: float, hi: float) -> "Array":
        """Clamp every element to ``[lo, hi]``."""
        ...
    def atan2_scalar(self, other: float) -> "Array":
        """Element-wise ``atan2(self, other)``."""
        ...
    def lerp_scalar(self, other: float, t: float) -> "Array":
        """Element-wise linear interpolation toward ``other``."""
        ...
    def fma(self, mul: float, add: float) -> "Array":
        """Fused multiply-add: ``self * mul + add``."""
        ...

    # --- Machine Learning / NN ---
    def sigmoid(self) -> "Array":
        """Element-wise sigmoid: ``1 / (1 + exp(-x))``."""
        ...
    def sigmoid_deriv(self) -> "Array":
        """Sigmoid derivative: ``sigmoid(x) * (1 - sigmoid(x))``."""
        ...
    def relu(self) -> "Array":
        """Rectified Linear Unit: ``max(0, x)``."""
        ...
    def relu_deriv(self) -> "Array":
        """ReLU derivative: ``1`` if ``x > 0`` else ``0``."""
        ...
    def leaky_relu(self, alpha: float) -> "Array":
        """Leaky ReLU: ``x`` if ``x > 0`` else ``alpha * x``."""
        ...
    def leaky_relu_deriv(self, alpha: float) -> "Array":
        """Leaky ReLU derivative."""
        ...
    def elu(self, alpha: float) -> "Array":
        """Exponential Linear Unit."""
        ...
    def selu(self) -> "Array":
        """Scaled Exponential Linear Unit."""
        ...
    def gelu(self) -> "Array":
        """Gaussian Error Linear Unit."""
        ...
    def swish(self) -> "Array":
        """Swish activation: ``x * sigmoid(x)``."""
        ...
    def mish(self) -> "Array":
        """Mish activation: ``x * tanh(softplus(x))``."""
        ...
    def softplus(self) -> "Array":
        """Softplus: ``ln(1 + exp(x))``."""
        ...
    def softmax(self) -> "Array":
        """Row-wise softmax normalization."""
        ...
    def log_softmax(self) -> "Array":
        """Numerically stable ``log(softmax(x))``."""
        ...
    def hardswish(self) -> "Array":
        """Hard Swish activation."""
        ...
    def mse_loss(self, target: "Array") -> float:
        """Mean Squared Error loss."""
        ...
    def mae_loss(self, target: "Array") -> float:
        """Mean Absolute Error loss."""
        ...
    def binary_cross_entropy(self, target: "Array") -> float:
        """Binary cross-entropy loss."""
        ...
    def cross_entropy_loss(self, labels: List[int]) -> float:
        """Categorical cross-entropy loss."""
        ...
    def batch_norm(self, mu: Vector, sigma: Vector, gamma: Vector, beta: Vector) -> "Array":
        """Batch normalization."""
        ...
    def layer_norm(self, eps: float) -> "Array":
        """Layer normalization."""
        ...
    def dropout(self, p: float) -> "Array":
        """Randomly zero elements with probability ``p``."""
        ...
    def max_pool2d(self, kernel_size: int) -> "Array":
        """2D max pooling."""
        ...
    def avg_pool2d(self, kernel_size: int) -> "Array":
        """2D average pooling."""
        ...
    def mse_grad(self, target: "Array") -> "Array":
        """Gradient of MSE loss w.r.t. predictions."""
        ...
    def softmax_ce_grad(self, labels: List[int]) -> "Array":
        """Gradient of softmax + cross-entropy loss."""
        ...

    # --- Interop ---
    def to_list(self) -> List[List[float]]:
        """Convert to a nested Python list."""
        ...
    def to_numpy(self) -> Any:
        """Convert to a NumPy ndarray."""
        ...
    def to_torch(self) -> Any:
        """Convert to a PyTorch tensor."""
        ...
    def to_jax(self) -> Any:
        """Convert to a JAX array."""
        ...
    def to_dataframe(self, columns: Optional[List[str]] = None) -> Any:
        """Convert to a pandas DataFrame."""
        ...
    def to_series(self, name: Optional[str] = None) -> Any:
        """Convert to a pandas Series (1D only)."""
        ...
    def to_flat_py(self) -> List[float]:
        """Flatten to a Python list of floats."""
        ...
    def to_flat_list(self) -> List[float]:
        """Alias for ``to_flat_py``."""
        ...
    def tolist(self) -> List[List[float]]:
        """Alias for ``to_list``."""
        ...
    def lazy(self) -> "LazyArray":
        """Bridge into a deferred execution pipeline."""
        ...
    def sklearn_shape(self) -> Tuple[int, int]:
        """Return ``(n_samples, n_features)`` for scikit-learn compatibility."""
        ...
    def validate_sklearn(self) -> None:
        """Raise if array is not 2D (scikit-learn requirement)."""
        ...
    def memory_bytes(self) -> int:
        """Actual memory usage in bytes."""
        ...
    def estimated_bytes(self) -> int:
        """Estimated memory usage in bytes."""
        ...

class Tensor:
    """Array wrapper with Autograd support for deep learning."""

    def __init__(self, data: Any, requires_grad: bool = False, dtype: Optional[str] = None) -> None:
        """Create a Tensor from an Array, list, or scalar."""
        ...
    
    @staticmethod
    def from_array(arr: Array, requires_grad: bool = False) -> "Tensor":
        """Create a Tensor from an existing Array."""
        ...

    @property
    def data(self) -> Array:
        """The underlying Array data."""
        ...
    @property
    def grad(self) -> Optional[Array]:
        """Accumulated gradient (None if not computed)."""
        ...
    @grad.setter
    def grad(self, value: Optional[Array]) -> None: ...
    @property
    def shape(self) -> Tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def dtype(self) -> str: ...
    @property
    def requires_grad(self) -> bool: ...
    @requires_grad.setter
    def requires_grad(self, value: bool) -> None: ...
    
    def backward(self) -> None:
        """Compute gradients via reverse-mode autodiff."""
        ...
    def zero_grad(self) -> None:
        """Reset accumulated gradient to None."""
        ...
    def build_topo(self) -> List["Tensor"]:
        """Return topological ordering of the computation graph."""
        ...
    def requires_grad_(self, requires_grad: bool) -> "Tensor":
        """Set requires_grad in-place, returns self."""
        ...
    def update_data(self, new_data: Array) -> None:
        """Replace underlying data (for optimizer weight updates)."""
        ...

    def __repr__(self) -> str: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __add__(self, other: Any) -> "Tensor": ...
    def __radd__(self, other: Any) -> "Tensor": ...
    def __sub__(self, other: Any) -> "Tensor": ...
    def __rsub__(self, other: Any) -> "Tensor": ...
    def __mul__(self, other: Any) -> "Tensor": ...
    def __rmul__(self, other: Any) -> "Tensor": ...
    def __truediv__(self, other: Any) -> "Tensor": ...
    def __rtruediv__(self, other: Any) -> "Tensor": ...
    def __matmul__(self, other: "Tensor") -> "Tensor": ...
    def __rmatmul__(self, other: "Tensor") -> "Tensor": ...
    def __neg__(self) -> "Tensor": ...
    def abs(self) -> "Tensor":
        """Element-wise absolute value (tracked by autograd)."""
        ...
    def exp(self) -> "Tensor":
        """Element-wise ``e^x`` (tracked by autograd)."""
        ...
    def log(self) -> "Tensor":
        """Element-wise natural logarithm (tracked by autograd)."""
        ...
    def tanh(self) -> "Tensor":
        """Element-wise hyperbolic tangent (tracked by autograd)."""
        ...
    def sigmoid(self) -> "Tensor":
        """Element-wise sigmoid (tracked by autograd)."""
        ...
    def relu(self) -> "Tensor":
        """Element-wise ReLU (tracked by autograd)."""
        ...
    def sum(self) -> "Tensor":
        """Sum all elements into a scalar Tensor (tracked by autograd)."""
        ...
    def mean(self) -> "Tensor":
        """Mean of all elements as a scalar Tensor (tracked by autograd)."""
        ...
    def reshape(self, shape: List[int]) -> "Tensor":
        """Reshape the Tensor (tracked by autograd)."""
        ...
    def transpose(self) -> "Tensor":
        """Transpose the Tensor (tracked by autograd)."""
        ...
    @property
    def t(self) -> "Tensor":
        """Shorthand for ``transpose()``."""
        ...

    @staticmethod
    def zeros(*shape: int, requires_grad: bool = False, **kwargs: Any) -> "Tensor":
        """Create a zero-filled Tensor."""
        ...
    @staticmethod
    def ones(*shape: int, requires_grad: bool = False, **kwargs: Any) -> "Tensor":
        """Create a ones-filled Tensor."""
        ...
    @staticmethod
    def randn(*shape: int, requires_grad: bool = False, **kwargs: Any) -> "Tensor":
        """Create a Tensor with standard normal random values."""
        ...

class SGD:
    """Stochastic Gradient Descent optimizer."""
    def __init__(self, params: List[Tensor], lr: float, momentum: float = 0.0) -> None:
        """Create an SGD optimizer for the given parameters."""
        ...
    def step(self) -> None:
        """Apply one optimization step."""
        ...
    def zero_grad(self) -> None:
        """Reset all parameter gradients."""
        ...

class Adam:
    """Adam optimizer."""
    def __init__(self, params: List[Tensor], lr: float = 0.001, beta1: float = 0.9, beta2: float = 0.999, eps: float = 1e-8) -> None:
        """Create an Adam optimizer for the given parameters."""
        ...
    def step(self) -> None:
        """Apply one optimization step."""
        ...
    def zero_grad(self) -> None:
        """Reset all parameter gradients."""
        ...

class LazyArray:
    """Deferred execution pipeline for fused array operations."""
    @staticmethod
    def open(path: str) -> "LazyArray":
        """Open a CSV file for lazy processing."""
        ...
    @staticmethod
    def open_bin(path: str, rows: int, cols: int) -> "LazyArray":
        """Open a binary file for lazy processing."""
        ...
    def peek(self) -> List[int]:
        """Return the shape without loading data."""
        ...
    def sin(self) -> "LazyArray": ...
    def cos(self) -> "LazyArray": ...
    def exp(self) -> "LazyArray": ...
    def sigmoid(self) -> "LazyArray": ...
    def add(self, val: float) -> "LazyArray": ...
    def mul(self, val: float) -> "LazyArray": ...
    def abs(self) -> "LazyArray": ...
    def pow(self, val: float) -> "LazyArray": ...
    def execute(self) -> Array:
        """Execute the pipeline and return the result as an Array."""
        ...
    def load(self) -> Array:
        """Load all data into memory as an Array."""
        ...
    def load_rows(self, start: int, end: int) -> Array:
        """Load rows ``[start, end)`` into memory."""
        ...
    def chunks(self, chunk_size: int) -> Iterator[Array]:
        """Iterate over the data in chunks of ``chunk_size`` rows."""
        ...
    def sum(self) -> float:
        """Sum all elements without loading the full array."""
        ...

class ChunkIterator:
    """Iterator yielding Array chunks."""
    def __iter__(self) -> "ChunkIterator": ...
    def __next__(self) -> Optional[Array]: ...

class MmapArray:
    """Memory-mapped array for processing datasets larger than RAM."""
    @staticmethod
    def mmap(path: str, rows: int, cols: int) -> "MmapArray":
        """Memory-map a binary file."""
        ...
    @property
    def shape(self) -> Tuple[int, int]:
        """Shape of the memory-mapped array."""
        ...
    def load_all(self) -> Array:
        """Load the entire file into an in-memory Array."""
        ...
    def get_element(self, r: int, c: int) -> float:
        """Read a single element at row ``r``, column ``c``."""
        ...
    def chunks(self, chunk_size: int) -> Iterator[Array]:
        """Iterate over the file in chunks of ``chunk_size`` rows."""
        ...

class MmapChunkIterator:
    """Iterator yielding Array chunks from a memory-mapped file."""
    def __iter__(self) -> "MmapChunkIterator": ...
    def __next__(self) -> Optional[Array]: ...

# Functional API
def arange(start: float, stop: float, step: float) -> Array:
    """Create a 1D Array from ``start`` to ``stop`` by ``step``."""
    ...
def zeros(rows: int, cols: int) -> Array:
    """Create a zero-filled Array."""
    ...
def ones(rows: int, cols: int) -> Array:
    """Create a ones-filled Array."""
    ...
def randn(*shape: int) -> Array:
    """Create an Array with standard normal random values."""
    ...
def rand_uniform(*shape: int) -> Array:
    """Create an Array with uniform random values in [0, 1)."""
    ...

# Submodules
linalg: Any
nn: Any
