"""
rmath.vector — high-performance parallelized element-wise math.

This module provides the `Vector` class and functional wrappers for performing 
massively parallel mathematical operations on 1D numeric data. 

Key Features:
    1. Parallel Execution: Operations on large vectors (>8,192 elements) 
       automatically use the Rayon thread pool, bypassing the Python GIL.
    2. Tiered Storage: Small vectors (<32 elements) are stored on the Rust 
       stack (Inline) for zero-allocation, L1-cache speed. Large vectors 
       use Arc-wrapped heap storage for efficient sharing.
    3. Loop Fusion: Use the `.lazy()` method to bridge into the `LazyPipeline`
       for even higher performance via loop fusion.

Example:
    >>> import rmath.vector as rv
    >>> v = rv.Vector.range(1_000_000)
    >>> result = (v.sin() * 2.0).sum()
"""

from typing import List, Sequence, Union, Tuple, Optional, Any

# ── Vector class ──────────────────────────────────────────────────────────────

class Vector:
    """A high-performance, parallelized 1D numeric container.
    
    The Vector class is optimized for linear scans and high-speed element-wise math.
    It supports standard Python operators and provides a vast library of 
    mathematical kernels.
    
    Vector objects are immutable (conceptually) in terms of their length, but
    support element-wise modification via `__setitem__` (which triggers 
    Copy-on-Write for shared heap storage).
    """

    def __init__(self, data: Union[Sequence[float], Any]) -> None:
        """Create a new Vector from a Python sequence or an RMath Array.
        
        Example:
            >>> v = rv.Vector([1.0, 2.0, 3.0])
        """
        ...

    # --- Constructors ---
    @staticmethod
    def range(start: float, stop: Optional[float] = None, step: float = 1.0) -> "Vector":
        """Create a Vector with a range of values.
        
        Usage: `Vector.range(stop)` or `Vector.range(start, stop, step)`.
        
        Example:
            >>> rv.Vector.range(5)
            Vector([0.0, 1.0, 2.0, 3.0, 4.0])
        """
        ...

    @staticmethod
    def arange(start: float, stop: Optional[float] = None, step: float = 1.0) -> "Vector":
        """Alias for `Vector.range()`."""
        ...

    @staticmethod
    def linspace(start: float, stop: float, num: int) -> "Vector":
        """Create a Vector with `num` evenly spaced values from `start` to `stop`.
        
        Example:
            >>> rv.Vector.linspace(0, 1, 5)
            Vector([0.0, 0.25, 0.5, 0.75, 1.0])
        """
        ...

    @staticmethod
    def zeros(n: int) -> "Vector":
        """Create a Vector of length `n` filled with zeros."""
        ...

    @staticmethod
    def ones(n: int) -> "Vector":
        """Create a Vector of length `n` filled with ones."""
        ...

    @staticmethod
    def full(n: int, val: float) -> "Vector":
        """Create a Vector of length `n` filled with `val`."""
        ...

    @staticmethod
    def random(n: int) -> "Vector":
        """Create a Vector of length `n` with uniform random values in [0, 1)."""
        ...

    @staticmethod
    def randn(n: int) -> "Vector":
        """Create a Vector of length `n` with standard normal (Gaussian) random values."""
        ...
    
    @staticmethod
    def rand_seeded(n: int, seed: int) -> "Vector":
        """Create a reproducible random Vector."""
        ...

    @staticmethod
    def sum_range(start: float, stop: Optional[float] = None, step: float = 1.0) -> float:
        """Calculate the arithmetic sum of a range in O(1) time without allocation.
        
        Example:
            >>> rv.Vector.sum_range(1, 101) # sum of 1..100
            5050.0
        """
        ...

    # --- Properties ---
    @property
    def shape(self) -> Tuple[int]:
        """The dimensions of the vector (always 1D)."""
        ...

    @property
    def ndim(self) -> int:
        """The number of dimensions (always 1)."""
        ...

    @property
    def size(self) -> int:
        """The total number of elements in the vector."""
        ...

    # --- Protocol ---
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> "VectorIter": ...
    def __contains__(self, val: float) -> bool: ...
    def __getitem__(self, index: Union[int, slice, List[int]]) -> Union[float, "Vector"]: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __delitem__(self, index: int) -> None: ...

    # --- Arithmetic Operators ---
    def __add__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __radd__(self, other: float) -> "Vector": ...
    def __sub__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __rsub__(self, other: float) -> "Vector": ...
    def __mul__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __rmul__(self, other: float) -> "Vector": ...
    def __truediv__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __rtruediv__(self, other: float) -> "Vector": ...
    def __floordiv__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __rfloordiv__(self, other: float) -> "Vector": ...
    def __mod__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __rmod__(self, other: float) -> "Vector": ...
    def __pow__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __rpow__(self, other: float) -> "Vector": ...
    def __neg__(self) -> "Vector": ...
    def __pos__(self) -> "Vector": ...
    def __abs__(self) -> "Vector": ...

    # --- Comparison Operators (Returns Vec[bool]) ---
    def __eq__(self, other: Any) -> List[bool]: ...
    def __ne__(self, other: Any) -> List[bool]: ...
    def __lt__(self, other: Union[float, "Vector"]) -> List[bool]: ...
    def __le__(self, other: Union[float, "Vector"]) -> List[bool]: ...
    def __gt__(self, other: Union[float, "Vector"]) -> List[bool]: ...
    def __ge__(self, other: Union[float, "Vector"]) -> List[bool]: ...

    # --- Conversion ---
    def to_list(self) -> List[float]:
        """Convert the Vector to a native Python list."""
        ...
    
    def tolist(self) -> List[float]:
        """Alias for `to_list()`."""
        ...

    def to_numpy(self, dtype: Optional[Any] = None) -> Any:
        """Convert to a NumPy array (requires numpy)."""
        ...

    def into_array(self) -> Any:
        """Zero-copy conversion to an RMath Array."""
        ...

    def __array__(self, dtype: Optional[Any] = None, copy: Optional[bool] = None) -> Any:
        """NumPy array interface."""
        ...

    def lazy(self) -> Any:
        """Bridge this Vector into a zero-copy LazyPipeline for operation chaining.
        
        Example:
            >>> v = rv.Vector.range(100)
            >>> v.lazy().sin().cos().sum()
        """
        ...

    # --- Named Arithmetic Methods ---
    def add(self, other: Union[float, "Vector"]) -> "Vector":
        """Element-wise addition. Accepts a scalar or another Vector."""
        ...
    def sub(self, other: Union[float, "Vector"]) -> "Vector":
        """Element-wise subtraction."""
        ...
    def mul(self, other: Union[float, "Vector"]) -> "Vector":
        """Element-wise multiplication."""
        ...
    def div(self, other: Union[float, "Vector"]) -> "Vector":
        """Element-wise division."""
        ...
    def pow(self, other: Union[float, "Vector"]) -> "Vector":
        """Element-wise exponentiation."""
        ...

    # --- Scalar Arithmetic Methods ---
    def add_scalar(self, s: float) -> "Vector":
        """Add a scalar to every element."""
        ...
    def sub_scalar(self, s: float) -> "Vector":
        """Subtract a scalar from every element."""
        ...
    def mul_scalar(self, s: float) -> "Vector":
        """Multiply every element by a scalar."""
        ...
    def div_scalar(self, s: float) -> "Vector":
        """Divide every element by a scalar. Raises ``ZeroDivisionError`` if ``s == 0``."""
        ...
    def pow_scalar(self, exp: float) -> "Vector":
        """Raise every element to the power ``exp``."""
        ...
    def clamp(self, lo: float, hi: float) -> "Vector":
        """Clamp every element to the range ``[lo, hi]``.

        Example:
            >>> Vector([1, 5, 10]).clamp(2, 8)
            Vector([2.0, 5.0, 8.0])
        """
        ...

    # --- Vector-Vector Methods ---
    def add_vec(self, other: "Vector") -> "Vector": ...
    def sub_vec(self, other: "Vector") -> "Vector": ...
    def mul_vec(self, other: "Vector") -> "Vector": ...
    def div_vec(self, other: "Vector") -> "Vector":
        """Element-wise division. Uses IEEE-754 semantics (0-divisors yield inf/nan)."""
        ...
    def dot(self, other: "Vector") -> float:
        """Calculate the dot product."""
        ...

    # --- Element-wise Math ---
    def ceil(self) -> "Vector":
        """Round each element up toward +∞."""
        ...
    def floor(self) -> "Vector":
        """Round each element down toward -∞."""
        ...
    def round(self) -> "Vector":
        """Round each element to the nearest integer."""
        ...
    def trunc(self) -> "Vector":
        """Truncate each element toward zero."""
        ...
    def fract(self) -> "Vector":
        """Return the fractional part of each element."""
        ...
    def abs(self) -> "Vector":
        """Element-wise absolute value."""
        ...
    def sqrt(self) -> "Vector":
        """Element-wise square root."""
        ...
    def cbrt(self) -> "Vector":
        """Element-wise cube root."""
        ...
    def signum(self) -> "Vector":
        """Element-wise sign: ``-1.0``, ``0.0``, or ``1.0``."""
        ...
    def recip(self) -> "Vector":
        """Element-wise reciprocal: ``1/x``."""
        ...
    def sigmoid(self) -> "Vector":
        """Element-wise sigmoid: ``1 / (1 + exp(-x))``."""
        ...
    def clip(self, lo: float, hi: float) -> "Vector":
        """Alias for ``clamp``."""
        ...

    # --- Trigonometric ---
    def sin(self) -> "Vector": ...
    def cos(self) -> "Vector": ...
    def tan(self) -> "Vector": ...
    def asin(self) -> "Vector": ...
    def acos(self) -> "Vector": ...
    def atan(self) -> "Vector": ...
    def sinh(self) -> "Vector": ...
    def cosh(self) -> "Vector": ...
    def tanh(self) -> "Vector": ...
    def atan2_scalar(self, x: float) -> "Vector":
        """Element-wise ``atan2(self[i], x)`` — angle in radians from the x-axis."""
        ...
    def hypot_scalar(self, y: float) -> "Vector":
        """Element-wise ``sqrt(self[i]² + y²)`` — hypotenuse length."""
        ...

    # --- Exp/Log ---
    def exp(self) -> "Vector":
        """Element-wise ``e^x``."""
        ...
    def exp2(self) -> "Vector":
        """Element-wise ``2^x``."""
        ...
    def expm1(self) -> "Vector":
        """Element-wise ``e^x - 1``, accurate for small x."""
        ...
    def log(self) -> "Vector":
        """Element-wise natural logarithm (base e)."""
        ...
    def log2(self) -> "Vector":
        """Element-wise base-2 logarithm."""
        ...
    def log10(self) -> "Vector":
        """Element-wise base-10 logarithm."""
        ...
    def log1p(self) -> "Vector":
        """Element-wise ``ln(1 + x)``, accurate for small x."""
        ...

    # --- Statistics & Reductions ---
    def sum(self) -> float:
        """Calculate the sum using Kahan compensation for high precision."""
        ...
    def prod(self) -> float:
        """Calculate the product of all elements."""
        ...
    def mean(self) -> float:
        """Calculate the arithmetic mean. Returns ``NaN`` for empty vectors."""
        ...
    def variance(self) -> float:
        """Calculate the sample variance (n-1 divisor)."""
        ...
    def pop_variance(self) -> float:
        """Calculate the population variance (n divisor)."""
        ...
    def std_dev(self) -> float:
        """Calculate the sample standard deviation."""
        ...
    def pop_std_dev(self) -> float:
        """Calculate the population standard deviation."""
        ...
    def median(self) -> float:
        """Calculate the median value."""
        ...
    def min(self) -> float:
        """Return the minimum element."""
        ...
    def max(self) -> float:
        """Return the maximum element."""
        ...
    def argmin(self) -> int:
        """Return the index of the minimum element."""
        ...
    def argmax(self) -> int:
        """Return the index of the maximum element."""
        ...
    def percentile(self, q: float) -> float:
        """Return the value at the ``q``-th percentile (0–100)."""
        ...
    
    def norm(self) -> float:
        """Calculate the Euclidean (L2) norm: sqrt(sum(x²))."""
        ...
    def norm_l1(self) -> float:
        """Calculate the Manhattan (L1) norm: sum(|x|)."""
        ...
    def norm_inf(self) -> float:
        """Calculate the Infinity (Max) norm: max(|x|)."""
        ...
    def norm_lp(self, p: float) -> float:
        """Calculate the p-norm: (sum(|x|^p))^(1/p)."""
        ...

    def standardize(self) -> "Vector":
        """Zero-mean, unit-variance transformation."""
        ...
    def softmax(self) -> "Vector":
        """Softmax transformation."""
        ...

    # --- Predicates (returns List[bool] or bool) ---
    def any(self) -> bool:
        """Return ``True`` if any element is non-zero."""
        ...
    def all(self) -> bool:
        """Return ``True`` if all elements are non-zero."""
        ...
    def isnan(self) -> List[bool]:
        """Element-wise NaN check."""
        ...
    def isfinite(self) -> List[bool]:
        """Element-wise finiteness check (not NaN or ±Inf)."""
        ...
    def isinf(self) -> List[bool]:
        """Element-wise infinity check."""
        ...
    def is_integer(self) -> List[bool]:
        """Element-wise check for integer values (e.g. 3.0 → True, 3.5 → False)."""
        ...
    def is_prime(self) -> List[bool]:
        """Element-wise primality check (elements are truncated to integers)."""
        ...

    # --- Filtering and selection ---
    def filter_gt(self, threshold: float) -> "Vector":
        """Return elements greater than threshold."""
        ...
    def filter_lt(self, threshold: float) -> "Vector":
        """Return elements less than threshold."""
        ...
    def filter_where(self, conditions: List[Tuple["Vector", str, float]]) -> "Vector":
        """Fully fused conditional filter — zero mask allocations."""
        ...
    @staticmethod
    def multi_filter_where(vectors: List["Vector"], conditions: List[Tuple["Vector", str, float]]) -> List["Vector"]:
        """Filter multiple vectors by the same conditions in a single pass."""
        ...
    def eq_mask(self, value: float) -> "Vector":
        """Generate a mask Vector: 1.0 where self[i] == value, 0.0 otherwise."""
        ...
    def where_(self, mask: List[bool], other: "Vector") -> "Vector":
        """Elementwise selection: where mask[i] -> self[i], else other[i]."""
        ...
    def sort(self) -> "Vector":
        """Return a sorted copy of the vector (ascending)."""
        ...
    def sort_desc(self) -> "Vector":
        """Return a sorted copy of the vector (descending)."""
        ...

    def filter_by_mask(self, mask: Union[List[bool], "Vector"]) -> "Vector":
        """Return elements where ``mask[i]`` is truthy.

        Parallelized via chunked filtering for large vectors (≥ 8 192 elements).
        Releases the GIL during execution.

        Args:
            mask: A ``Vector`` of 1.0/0.0 values or a Python list of bools.
                  Must have the same length as this vector.

        Example:
            >>> v = Vector([1, 2, 3, 4])
            >>> v.filter_by_mask([True, False, True, False])
            Vector([1.0, 3.0])
        """
        ...

    def filter_by_masks(self, masks: List["Vector"]) -> "Vector":
        """Filter elements where **all** mask vectors are non-zero (logical AND).

        Fuses the AND check in a single pass — no intermediate combined mask
        is allocated, saving O(N) memory per additional mask.
        Parallelized and GIL-releasing.

        Args:
            masks: A list of ``Vector`` masks (1.0/0.0).
                   All must have the same length as this vector.

        Example:
            >>> v = Vector([1, 2, 3, 4, 5])
            >>> m1 = Vector([1, 0, 1, 0, 1])
            >>> m2 = Vector([1, 1, 0, 0, 1])
            >>> v.filter_by_masks([m1, m2])
            Vector([1.0, 5.0])
        """
        ...

    def filter_where(
        self,
        conditions: List[Tuple["Vector", str, float]],
        mode: str = "all",
    ) -> "Vector":
        """Fully fused conditional filter — **zero mask allocations**.

        Checks conditions directly on source vectors per-element without
        materializing any intermediate mask vector.

        Args:
            conditions: List of ``(vector, operator, threshold)`` tuples.
                Supported operators: ``"lt"``/``"<"``, ``"gt"``/``">"``,
                ``"le"``/``"<="``, ``"ge"``/``">="``, ``"eq"``/``"=="``,
                ``"ne"``/``"!="``.
            mode: ``"all"`` (AND, default) or ``"any"`` (OR).

        Example:
            >>> data = Vector([10, 20, 30, 40, 50])
            >>> income = Vector([100, 200, 50, 300, 80])
            >>> data.filter_where([(income, "lt", 150)])
            Vector([10.0, 30.0, 50.0])
        """
        ...

    @staticmethod
    def multi_filter_where(
        vectors: List["Vector"],
        conditions: List[Tuple["Vector", str, float]],
        mode: str = "all",
    ) -> List["Vector"]:
        """Filter multiple vectors by the same conditions in a single pass.

        Checks conditions **once** per element, then gathers from all data
        vectors simultaneously.  Significantly faster than calling
        ``filter_where`` separately on each vector.

        Parallelized and GIL-releasing.

        Args:
            vectors: List of data ``Vector`` objects to filter (must all
                     have the same length).
            conditions: Same format as ``filter_where``.
            mode: ``"all"`` (AND, default) or ``"any"`` (OR).

        Returns:
            A list of filtered ``Vector`` objects in the same order as
            the input.

        Example:
            >>> a = Vector([1, 2, 3, 4, 5])
            >>> b = Vector([10, 20, 30, 40, 50])
            >>> cond = Vector([100, 200, 50, 300, 80])
            >>> Vector.multi_filter_where([a, b], [(cond, "lt", 150)])
            [Vector([1.0, 3.0, 5.0]), Vector([10.0, 30.0, 50.0])]
        """
        ...

    def gt_mask(self, threshold: float) -> "Vector":
        """Generate a mask: ``1.0`` where ``self[i] > threshold``, ``0.0`` otherwise.

        Use with ``filter_by_mask`` or ``filter_by_masks`` for conditional filtering.
        For zero-allocation filtering, prefer ``filter_where`` instead.

        Example:
            >>> v = Vector([10, 20, 30, 40])
            >>> v.gt_mask(25)
            Vector([0.0, 0.0, 1.0, 1.0])
        """
        ...

    def lt_mask(self, threshold: float) -> "Vector":
        """Generate a mask: ``1.0`` where ``self[i] < threshold``, ``0.0`` otherwise.

        Example:
            >>> v = Vector([10, 20, 30, 40])
            >>> v.lt_mask(25)
            Vector([1.0, 1.0, 0.0, 0.0])
        """
        ...

    def eq_mask(self, value: float) -> "Vector":
        """Generate a mask: ``1.0`` where ``self[i] == value``, ``0.0`` otherwise.

        Example:
            >>> v = Vector([1, 2, 3, 2, 1])
            >>> v.eq_mask(2.0)
            Vector([0.0, 1.0, 0.0, 1.0, 0.0])
        """
        ...

    def filter_gt(self, threshold: float) -> "Vector":
        """Return only elements greater than ``threshold``.

        Shorthand for ``v.filter_by_mask(v.gt_mask(threshold))``.

        Example:
            >>> Vector([10, 20, 30, 40]).filter_gt(25)
            Vector([30.0, 40.0])
        """
        ...

    def filter_lt(self, threshold: float) -> "Vector":
        """Return only elements less than ``threshold``.

        Shorthand for ``v.filter_by_mask(v.lt_mask(threshold))``.

        Example:
            >>> Vector([10, 20, 30, 40]).filter_lt(25)
            Vector([10.0, 20.0])
        """
        ...

    def where_(self, mask: List[bool], other: "Vector") -> "Vector":
        """Element-wise selection: pick from ``self`` where mask is True,
        from ``other`` where mask is False.

        Similar to ``numpy.where(mask, self, other)``.

        Args:
            mask: A list of bools (same length as ``self``).
            other: A ``Vector`` to pick from when mask is False.

        Example:
            >>> a = Vector([1, 2, 3])
            >>> b = Vector([10, 20, 30])
            >>> a.where_([True, False, True], b)
            Vector([1.0, 20.0, 3.0])
        """
        ...

    # --- Sorting & Reordering ---
    def sort(self) -> "Vector":
        """Return a new Vector with elements sorted in ascending order."""
        ...
    def sort_desc(self) -> "Vector":
        """Return a new Vector with elements sorted in descending order."""
        ...
    def argsort(self) -> List[int]:
        """Return the indices that would sort this vector."""
        ...
    def reverse(self) -> "Vector":
        """Return a new Vector with elements in reversed order."""
        ...
    def unique(self) -> "Vector":
        """Return a new Vector containing only unique elements (sorted)."""
        ...

    # --- Cumulative Operations ---
    def cumsum(self) -> "Vector":
        """Cumulative sum: ``out[i] = sum(self[0..=i])``."""
        ...
    def cumprod(self) -> "Vector":
        """Cumulative product: ``out[i] = prod(self[0..=i])``."""
        ...
    def diff(self) -> "Vector":
        """First-order discrete difference: ``out[i] = self[i+1] - self[i]``.

        Returns a Vector with length ``n - 1``.
        """
        ...

    # --- Shaping & Slicing ---
    def head(self, n: int) -> "Vector":
        """Return the first ``n`` elements."""
        ...
    def tail(self, n: int) -> "Vector":
        """Return the last ``n`` elements."""
        ...
    def chunks(self, chunk_size: int) -> List["Vector"]:
        """Split into a list of sub-vectors of size ``chunk_size``.

        The last chunk may be shorter if the length is not evenly divisible.
        """
        ...
    def append(self, val: float) -> "Vector":
        """Return a new Vector with ``val`` added at the end."""
        ...
    def extend(self, other: "Vector") -> "Vector":
        """Return a new Vector by concatenating ``other`` at the end."""
        ...

    # --- Specialized Math ---
    def lerp_scalar(self, other: float, t: float) -> "Vector":
        """Element-wise linear interpolation: ``self[i] + t * (other - self[i])``."""
        ...

class VectorIter:
    """An iterator over Vector elements."""
    def __next__(self) -> float: ...
    def __iter__(self) -> "VectorIter": ...

class ComplexVector:
    """A high-performance container for complex-valued signals (f64 + i*f64).
    
    Ideal for FFTs and digital signal processing.
    """
    def __init__(self, real: Sequence[float], imag: Sequence[float]) -> None: ...
    def to_mags(self) -> Vector:
        """Calculate the magnitude (modulus) of each element."""
        ...
    def to_phases(self) -> Vector:
        """Calculate the phase angle (argument) of each element."""
        ...
    def mask_inplace(self, mask: List[bool]) -> None:
        """Apply a boolean mask in-place."""
        ...
    def __len__(self) -> int: ...

# ── Functional API (Functional Wrappers) ─────────────────────────────────────

def rand(n: int) -> Vector: ...
def randn(n: int) -> Vector: ...
def rand_seeded(n: int, seed: int) -> Vector: ...
def randn_seeded(n: int, seed: int) -> Vector: ...

def linspace(start: float, stop: float, num: int) -> Vector: ...
def arange(start: float, stop: Optional[float] = None, step: float = 1.0) -> Vector: ...
def range(start: float, stop: Optional[float] = None, step: float = 1.0) -> Vector: ...
def sum_range(start: float, stop: Optional[float] = None, step: float = 1.0) -> float: ...

def zeros(n: int) -> Vector: ...
def ones(n: int) -> Vector: ...
def full(n: int, val: float) -> Vector: ...

def sin(v: Vector)  -> Vector: ...
def cos(v: Vector)  -> Vector: ...
def tan(v: Vector)  -> Vector: ...
def asin(v: Vector) -> Vector: ...
def acos(v: Vector) -> Vector: ...
def atan(v: Vector) -> Vector: ...
def sinh(v: Vector) -> Vector: ...
def cosh(v: Vector) -> Vector: ...
def tanh(v: Vector) -> Vector: ...
def exp(v: Vector)  -> Vector: ...
def exp2(v: Vector) -> Vector: ...
def expm1(v: Vector)-> Vector: ...
def log(v: Vector)  -> Vector: ...
def log2(v: Vector) -> Vector: ...
def log10(v: Vector)-> Vector: ...
def log1p(v: Vector)-> Vector: ...
def sqrt(v: Vector) -> Vector: ...
def cbrt(v: Vector) -> Vector: ...
def abs(v: Vector)  -> Vector: ...
def ceil(v: Vector) -> Vector: ...
def floor(v: Vector)-> Vector: ...
def round(v: Vector)-> Vector: ...
def trunc(v: Vector)-> Vector: ...
def fract(v: Vector)-> Vector: ...
def signum(v: Vector)->Vector: ...
def recip(v: Vector)-> Vector: ...

def vsum(v: Vector) -> float: ...
def prod(v: Vector) -> float: ...
def mean(v: Vector) -> float: ...
def variance(v: Vector) -> float: ...
def pop_variance(v: Vector) -> float: ...
def std_dev(v: Vector) -> float: ...
def pop_std_dev(v: Vector) -> float: ...
def median(v: Vector) -> float: ...
def percentile(v: Vector, q: float) -> float: ...
def vmin(v: Vector) -> float: ...
def vmax(v: Vector) -> float: ...
def argmin(v: Vector) -> int: ...
def argmax(v: Vector) -> int: ...
def norm(v: Vector) -> float: ...
def norm_l1(v: Vector) -> float: ...
def norm_inf(v: Vector) -> float: ...
def norm_lp(v: Vector, p: float) -> float: ...
def dot(v1: Vector, v2: Vector) -> float: ...

def add_scalar(v: Vector, s: float) -> Vector: ...
def sub_scalar(v: Vector, s: float) -> Vector: ...
def mul_scalar(v: Vector, s: float) -> Vector: ...
def div_scalar(v: Vector, s: float) -> Vector: ...
def pow_scalar(v: Vector, e: float) -> Vector: ...
def clamp(v: Vector, lo: float, hi: float) -> Vector: ...

def add_vec(v1: Vector, v2: Vector) -> Vector: ...
def sub_vec(v1: Vector, v2: Vector) -> Vector: ...
def mul_vec(v1: Vector, v2: Vector) -> Vector: ...
def div_vec(v1: Vector, v2: Vector) -> Vector: ...

def isnan(v: Vector)     -> List[bool]: ...
def isfinite(v: Vector)  -> List[bool]: ...
def isinf(v: Vector)     -> List[bool]: ...
def is_integer(v: Vector)-> List[bool]: ...
def is_prime(v: Vector)  -> List[bool]: ...
