"""
rmath.vector — high-performance parallelized element-wise math.

This module provides the `Vector` class and functional wrappers for performing 
massively parallel mathematical operations on 1D numeric data. 

Key Features:
    1. Parallel Execution: Operations on large vectors (>8,192 elements) 
       automatically use the Rayon thread pool, bypassing the Python GIL.
    2. Tiered Storage: Small vectors (<32 elements) are stored on the Rust 
       stack (Inline) for zero-allocation, L1-cache speed. Large vectors 
       use Arc-wrapped heap storage for efficient sharing.
    3. Loop Fusion: Use the `.lazy()` method to bridge into the `LazyPipeline`
       for even higher performance via loop fusion.

Example:
    >>> import rmath.vector as rv
    >>> v = rv.Vector.range(1_000_000)
    >>> result = (v.sin() * 2.0).sum()
"""

from typing import List, Sequence, Union, Tuple, Optional, Any

# ── Vector class ──────────────────────────────────────────────────────────────

class Vector:
    """A high-performance, parallelized 1D numeric container.
    
    The Vector class is optimized for linear scans and high-speed element-wise math.
    It supports standard Python operators and provides a vast library of 
    mathematical kernels.
    
    Vector objects are immutable (conceptually) in terms of their length, but
    support element-wise modification via `__setitem__` (which triggers 
    Copy-on-Write for shared heap storage).
    """

    def __init__(self, data: Union[Sequence[float], Any]) -> None:
        """Create a new Vector from a Python sequence or an RMath Array.
        
        Example:
            >>> v = rv.Vector([1.0, 2.0, 3.0])
        """
        ...

    # --- Constructors ---
    @staticmethod
    def range(start: float, stop: Optional[float] = None, step: float = 1.0) -> "Vector":
        """Create a Vector with a range of values.
        
        Usage: `Vector.range(stop)` or `Vector.range(start, stop, step)`.
        
        Example:
            >>> rv.Vector.range(5)
            Vector([0.0, 1.0, 2.0, 3.0, 4.0])
        """
        ...

    @staticmethod
    def arange(start: float, stop: Optional[float] = None, step: float = 1.0) -> "Vector":
        """Alias for `Vector.range()`."""
        ...

    @staticmethod
    def linspace(start: float, stop: float, num: int) -> "Vector":
        """Create a Vector with `num` evenly spaced values from `start` to `stop`.
        
        Example:
            >>> rv.Vector.linspace(0, 1, 5)
            Vector([0.0, 0.25, 0.5, 0.75, 1.0])
        """
        ...

    @staticmethod
    def zeros(n: int) -> "Vector":
        """Create a Vector of length `n` filled with zeros."""
        ...

    @staticmethod
    def ones(n: int) -> "Vector":
        """Create a Vector of length `n` filled with ones."""
        ...

    @staticmethod
    def full(n: int, val: float) -> "Vector":
        """Create a Vector of length `n` filled with `val`."""
        ...

    @staticmethod
    def random(n: int) -> "Vector":
        """Create a Vector of length `n` with uniform random values in [0, 1)."""
        ...

    @staticmethod
    def randn(n: int) -> "Vector":
        """Create a Vector of length `n` with standard normal (Gaussian) random values."""
        ...
    
    @staticmethod
    def rand_seeded(n: int, seed: int) -> "Vector":
        """Create a reproducible random Vector."""
        ...

    @staticmethod
    def sum_range(start: float, stop: Optional[float] = None, step: float = 1.0) -> float:
        """Calculate the arithmetic sum of a range in O(1) time without allocation.
        
        Example:
            >>> rv.Vector.sum_range(1, 101) # sum of 1..100
            5050.0
        """
        ...

    # --- Properties ---
    @property
    def shape(self) -> Tuple[int]:
        """The dimensions of the vector (always 1D)."""
        ...

    @property
    def ndim(self) -> int:
        """The number of dimensions (always 1)."""
        ...

    @property
    def size(self) -> int:
        """The total number of elements in the vector."""
        ...

    # --- Protocol ---
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> "VectorIter": ...
    def __contains__(self, val: float) -> bool: ...
    def __getitem__(self, index: Union[int, slice, List[int]]) -> Union[float, "Vector"]: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __delitem__(self, index: int) -> None: ...

    # --- Arithmetic Operators ---
    def __add__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __radd__(self, other: float) -> "Vector": ...
    def __sub__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __rsub__(self, other: float) -> "Vector": ...
    def __mul__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __rmul__(self, other: float) -> "Vector": ...
    def __truediv__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __rtruediv__(self, other: float) -> "Vector": ...
    def __floordiv__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __rfloordiv__(self, other: float) -> "Vector": ...
    def __mod__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __rmod__(self, other: float) -> "Vector": ...
    def __pow__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __rpow__(self, other: float) -> "Vector": ...
    def __neg__(self) -> "Vector": ...
    def __pos__(self) -> "Vector": ...
    def __abs__(self) -> "Vector": ...
    def __matmul__(self, other: "Vector") -> float:
        """Dot product using the `@` operator."""
        ...

    # --- Comparison Operators (Returns Vec[bool]) ---
    def __eq__(self, other: Any) -> List[bool]: ...
    def __ne__(self, other: Any) -> List[bool]: ...
    def __lt__(self, other: Union[float, "Vector"]) -> List[bool]: ...
    def __le__(self, other: Union[float, "Vector"]) -> List[bool]: ...
    def __gt__(self, other: Union[float, "Vector"]) -> List[bool]: ...
    def __ge__(self, other: Union[float, "Vector"]) -> List[bool]: ...

    # --- Conversion ---
    def to_list(self) -> List[float]:
        """Convert the Vector to a native Python list."""
        ...
    
    def tolist(self) -> List[float]:
        """Alias for `to_list()`."""
        ...

    def to_numpy(self, dtype: Optional[Any] = None) -> Any:
        """Convert to a NumPy array (requires numpy)."""
        ...

    def into_array(self) -> Any:
        """Zero-copy conversion to an RMath Array."""
        ...

    def __array__(self, dtype: Optional[Any] = None, copy: Optional[bool] = None) -> Any:
        """NumPy array interface."""
        ...

    def lazy(self) -> Any:
        """Bridge this Vector into a zero-copy LazyPipeline for operation chaining.
        
        Example:
            >>> v = rv.Vector.range(100)
            >>> v.lazy().sin().cos().sum()
        """
        ...

    # --- Named Arithmetic Methods ---
    def add(self, other: Union[float, "Vector"]) -> "Vector": ...
    def sub(self, other: Union[float, "Vector"]) -> "Vector": ...
    def mul(self, other: Union[float, "Vector"]) -> "Vector": ...
    def div(self, other: Union[float, "Vector"]) -> "Vector": ...
    def pow(self, other: Union[float, "Vector"]) -> "Vector": ...

    # --- Scalar Arithmetic Methods ---
    def add_scalar(self, s: float) -> "Vector": ...
    def sub_scalar(self, s: float) -> "Vector": ...
    def mul_scalar(self, s: float) -> "Vector": ...
    def div_scalar(self, s: float) -> "Vector":
        """Divide every element by a scalar. Raises `ZeroDivisionError` if `s == 0`."""
        ...
    def pow_scalar(self, exp: float) -> "Vector": ...
    def clamp(self, lo: float, hi: float) -> "Vector":
        """Clamp every element to the range [lo, hi]."""
        ...

    # --- Vector-Vector Methods ---
    def add_vec(self, other: "Vector") -> "Vector": ...
    def sub_vec(self, other: "Vector") -> "Vector": ...
    def mul_vec(self, other: "Vector") -> "Vector": ...
    def div_vec(self, other: "Vector") -> "Vector":
        """Element-wise division. Uses IEEE-754 semantics (0-divisors yield inf/nan)."""
        ...
    def dot(self, other: "Vector") -> float:
        """Calculate the dot product."""
        ...

    # --- Element-wise Math ---
    def ceil(self) -> "Vector": ...
    def floor(self) -> "Vector": ...
    def round(self) -> "Vector": ...
    def trunc(self) -> "Vector": ...
    def fract(self) -> "Vector": ...
    def abs(self) -> "Vector": ...
    def sqrt(self) -> "Vector": ...
    def cbrt(self) -> "Vector": ...
    def signum(self) -> "Vector": ...
    def recip(self) -> "Vector":
        """Calculate element-wise reciprocal (1/x)."""
        ...
    def sigmoid(self) -> "Vector": ...
    def clip(self, lo: float, hi: float) -> "Vector": ...

    # --- Trigonometric ---
    def sin(self) -> "Vector": ...
    def cos(self) -> "Vector": ...
    def tan(self) -> "Vector": ...
    def asin(self) -> "Vector": ...
    def acos(self) -> "Vector": ...
    def atan(self) -> "Vector": ...
    def sinh(self) -> "Vector": ...
    def cosh(self) -> "Vector": ...
    def tanh(self) -> "Vector": ...
    def atan2_scalar(self, x: float) -> "Vector": ...
    def hypot_scalar(self, y: float) -> "Vector": ...

    # --- Exp/Log ---
    def exp(self) -> "Vector": ...
    def exp2(self) -> "Vector": ...
    def expm1(self) -> "Vector": ...
    def log(self) -> "Vector": ...
    def log2(self) -> "Vector": ...
    def log10(self) -> "Vector": ...
    def log1p(self) -> "Vector": ...

    # --- Statistics & Reductions ---
    def sum(self) -> float:
        """Calculate the sum using Kahan compensation for high precision."""
        ...
    def prod(self) -> float: ...
    def mean(self) -> float:
        """Calculate the arithmetic mean. Returns `NaN` for empty vectors."""
        ...
    def variance(self) -> float:
        """Calculate the sample variance (n-1 divisor)."""
        ...
    def pop_variance(self) -> float:
        """Calculate the population variance (n divisor)."""
        ...
    def std_dev(self) -> float: ...
    def pop_std_dev(self) -> float: ...
    def median(self) -> float: ...
    def min(self) -> float: ...
    def max(self) -> float: ...
    def argmin(self) -> int: ...
    def argmax(self) -> int: ...
    def percentile(self, q: float) -> float: ...
    
    def norm(self) -> float:
        """Calculate the Euclidean (L2) norm: sqrt(sum(x²))."""
        ...
    def norm_l1(self) -> float:
        """Calculate the Manhattan (L1) norm: sum(|x|)."""
        ...
    def norm_inf(self) -> float:
        """Calculate the Infinity (Max) norm: max(|x|)."""
        ...
    def norm_lp(self, p: float) -> float:
        """Calculate the p-norm: (sum(|x|^p))^(1/p)."""
        ...

    def standardize(self) -> "Vector":
        """Zero-mean, unit-variance transformation."""
        ...
    def softmax(self) -> "Vector":
        """Softmax transformation."""
        ...

    # --- Predicates (returns List[bool] or bool) ---
    def any(self) -> bool: ...
    def all(self) -> bool: ...
    def isnan(self) -> List[bool]: ...
    def isfinite(self) -> List[bool]: ...
    def isinf(self) -> List[bool]: ...
    def is_integer(self) -> List[bool]: ...
    def is_prime(self) -> List[bool]: ...

    # --- Filtering and selection ---
    def filter_by_mask(self, mask: Union[List[bool], "Vector"]) -> "Vector": ...
    def gt_mask(self, threshold: float) -> "Vector": ...
    def lt_mask(self, threshold: float) -> "Vector": ...
    def eq_mask(self, value: float) -> "Vector": ...
    def filter_gt(self, threshold: float) -> "Vector": ...
    def filter_lt(self, threshold: float) -> "Vector": ...
    def where_(self, mask: List[bool], other: "Vector") -> "Vector": ...

    # --- Sorting & Reordering ---
    def sort(self) -> "Vector":
        """Return a new Vector with elements sorted in ascending order."""
        ...
    def sort_desc(self) -> "Vector":
        """Return a new Vector with elements sorted in descending order."""
        ...
    def argsort(self) -> List[int]:
        """Return the indices that would sort this vector."""
        ...
    def reverse(self) -> "Vector": ...
    def unique(self) -> "Vector":
        """Return a new Vector containing only unique elements (sorted)."""
        ...

    # --- Cumulative Operations ---
    def cumsum(self) -> "Vector": ...
    def cumprod(self) -> "Vector": ...
    def diff(self) -> "Vector":
        """Calculate the first-order discrete difference: out[i] = v[i] - v[i-1]."""
        ...

    # --- Shaping & Slicing ---
    def head(self, n: int) -> "Vector": ...
    def tail(self, n: int) -> "Vector": ...
    def chunks(self, chunk_size: int) -> List["Vector"]: ...
    def append(self, val: float) -> "Vector": ...
    def extend(self, other: "Vector") -> "Vector": ...

    # --- Specialized Math ---
    def lerp_scalar(self, other: float, t: float) -> "Vector": ...

class VectorIter:
    """An iterator over Vector elements."""
    def __next__(self) -> float: ...
    def __iter__(self) -> "VectorIter": ...

class ComplexVector:
    """A high-performance container for complex-valued signals (f64 + i*f64).
    
    Ideal for FFTs and digital signal processing.
    """
    def __init__(self, real: Sequence[float], imag: Sequence[float]) -> None: ...
    def to_mags(self) -> Vector:
        """Calculate the magnitude (modulus) of each element."""
        ...
    def to_phases(self) -> Vector:
        """Calculate the phase angle (argument) of each element."""
        ...
    def mask_inplace(self, mask: List[bool]) -> None:
        """Apply a boolean mask in-place."""
        ...
    def __len__(self) -> int: ...

# ── Functional API (Functional Wrappers) ─────────────────────────────────────

def rand(n: int) -> Vector: ...
def randn(n: int) -> Vector: ...
def rand_seeded(n: int, seed: int) -> Vector: ...
def randn_seeded(n: int, seed: int) -> Vector: ...

def linspace(start: float, stop: float, num: int) -> Vector: ...
def arange(start: float, stop: Optional[float] = None, step: float = 1.0) -> Vector: ...
def range(start: float, stop: Optional[float] = None, step: float = 1.0) -> Vector: ...
def sum_range(start: float, stop: Optional[float] = None, step: float = 1.0) -> float: ...

def zeros(n: int) -> Vector: ...
def ones(n: int) -> Vector: ...
def full(n: int, val: float) -> Vector: ...

def sin(v: Vector)  -> Vector: ...
def cos(v: Vector)  -> Vector: ...
def tan(v: Vector)  -> Vector: ...
def asin(v: Vector) -> Vector: ...
def acos(v: Vector) -> Vector: ...
def atan(v: Vector) -> Vector: ...
def sinh(v: Vector) -> Vector: ...
def cosh(v: Vector) -> Vector: ...
def tanh(v: Vector) -> Vector: ...
def exp(v: Vector)  -> Vector: ...
def exp2(v: Vector) -> Vector: ...
def expm1(v: Vector)-> Vector: ...
def log(v: Vector)  -> Vector: ...
def log2(v: Vector) -> Vector: ...
def log10(v: Vector)-> Vector: ...
def log1p(v: Vector)-> Vector: ...
def sqrt(v: Vector) -> Vector: ...
def cbrt(v: Vector) -> Vector: ...
def abs(v: Vector)  -> Vector: ...
def ceil(v: Vector) -> Vector: ...
def floor(v: Vector)-> Vector: ...
def round(v: Vector)-> Vector: ...
def trunc(v: Vector)-> Vector: ...
def fract(v: Vector)-> Vector: ...
def signum(v: Vector)->Vector: ...
def recip(v: Vector)-> Vector: ...

def vsum(v: Vector) -> float: ...
def prod(v: Vector) -> float: ...
def mean(v: Vector) -> float: ...
def variance(v: Vector) -> float: ...
def pop_variance(v: Vector) -> float: ...
def std_dev(v: Vector) -> float: ...
def pop_std_dev(v: Vector) -> float: ...
def median(v: Vector) -> float: ...
def percentile(v: Vector, q: float) -> float: ...
def vmin(v: Vector) -> float: ...
def vmax(v: Vector) -> float: ...
def argmin(v: Vector) -> int: ...
def argmax(v: Vector) -> int: ...
def norm(v: Vector) -> float: ...
def norm_l1(v: Vector) -> float: ...
def norm_inf(v: Vector) -> float: ...
def norm_lp(v: Vector, p: float) -> float: ...
def dot(v1: Vector, v2: Vector) -> float: ...

def add_scalar(v: Vector, s: float) -> Vector: ...
def sub_scalar(v: Vector, s: float) -> Vector: ...
def mul_scalar(v: Vector, s: float) -> Vector: ...
def div_scalar(v: Vector, s: float) -> Vector: ...
def pow_scalar(v: Vector, e: float) -> Vector: ...
def clamp(v: Vector, lo: float, hi: float) -> Vector: ...

def add_vec(v1: Vector, v2: Vector) -> Vector: ...
def sub_vec(v1: Vector, v2: Vector) -> Vector: ...
def mul_vec(v1: Vector, v2: Vector) -> Vector: ...
def div_vec(v1: Vector, v2: Vector) -> Vector: ...

def isnan(v: Vector)     -> List[bool]: ...
def isfinite(v: Vector)  -> List[bool]: ...
def isinf(v: Vector)     -> List[bool]: ...
def is_integer(v: Vector)-> List[bool]: ...
def is_prime(v: Vector)  -> List[bool]: ...
