from typing import Union, Tuple, List
from .array import Array
from .vector import Vector

def inv(matrix: Array) -> Array:
    """Compute the inverse of a square matrix."""
    ...

def det(matrix: Array) -> float:
    """Compute the determinant of a square matrix."""
    ...

def solve(a: Array, b: Array) -> Array:
    """Solve the linear system Ax = B for x."""
    ...

def qr(matrix: Array) -> Tuple[Array, Array]:
    """Perform QR decomposition."""
    ...

def svd(matrix: Array) -> Tuple[Array, Vector, Array]:
    """Perform Singular Value Decomposition."""
    ...

def eigh(matrix: Array) -> Tuple[Array, Vector]:
    """Eigenvalues and eigenvectors of a symmetric matrix."""
    ...

def cholesky(matrix: Array) -> Array:
    """Cholesky decomposition of a PD matrix."""
    ...

def transpose(matrix: Array) -> Array: ...
def rank(matrix: Array) -> int: ...
def pseudo_inv(matrix: Array) -> Array: ...
def gram_matrix(matrix: Array) -> Array: ...
def covariance(matrix: Array) -> Array: ...
