"""
rmath.vector — parallelized element-wise math on Python lists AND the Vector class.
Functional wrappers take list[float]; Vector class provides OOP + chaining + operators.
Maintain this file: stubs/rmath/vector.pyi
"""

from typing import List, Sequence, Union, Tuple

# ── Vector class ──────────────────────────────────────────────────────────────

class Vector:
    """Parallel element-wise math on a 1-D sequence of f64.

    Supports operator overloading (+, -, *, /, @, unary-) for both
    scalar (float) and Vector operands.  All heavy loops run on Rayon
    thread pool with zero GIL holding.

    Chain example::
        result = Vector.range(1, 1_000_001).add_scalar(-500_000).div_scalar(250_000).sin().sum()
    """

    def __init__(self, data: Sequence[float]) -> None: ...

    # --- Constructors ---
    @staticmethod
    def range(start_or_stop: float, stop: float = ..., step: float = 1.0) -> "Vector": ...
    @staticmethod
    def linspace(start: float, stop: float, num: int) -> "Vector": ...
    @staticmethod
    def sum_range(start_or_stop: float, stop: float = ..., step: float = 1.0) -> float: ...

    # --- Protocol ---
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...

    # --- Operators  (scalar OR Vector dispatch) ---
    def __add__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __radd__(self, other: float) -> "Vector": ...
    def __sub__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __rsub__(self, other: float) -> "Vector": ...
    def __mul__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __rmul__(self, other: float) -> "Vector": ...
    def __truediv__(self, other: Union[float, "Vector"]) -> "Vector": ...
    def __neg__(self) -> "Vector": ...
    def __matmul__(self, other: "Vector") -> float: ...  # dot product

    # --- Conversion ---
    def to_list(self) -> List[float]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...

    # --- Scalar arithmetic ---
    def add_scalar(self, s: float) -> "Vector": ...
    def sub_scalar(self, s: float) -> "Vector": ...
    def mul_scalar(self, s: float) -> "Vector": ...
    def div_scalar(self, s: float) -> "Vector": ...   # raises ZeroDivisionError
    def pow_scalar(self, exp: float) -> "Vector": ...
    def clamp(self, lo: float, hi: float) -> "Vector": ...

    # --- Vector-vector element-wise ---
    def add_vec(self, other: "Vector") -> "Vector": ...
    def sub_vec(self, other: "Vector") -> "Vector": ...
    def mul_vec(self, other: "Vector") -> "Vector": ...
    def div_vec(self, other: "Vector") -> "Vector": ...   # raises ZeroDivisionError
    def dot(self, other: "Vector") -> float: ...

    # --- Rounding ---
    def ceil(self) -> "Vector": ...
    def floor(self) -> "Vector": ...
    def round(self) -> "Vector": ...
    def trunc(self) -> "Vector": ...
    def abs(self) -> "Vector": ...
    def sqrt(self) -> "Vector": ...
    def cbrt(self) -> "Vector": ...

    # --- Trig ---
    def sin(self) -> "Vector": ...
    def cos(self) -> "Vector": ...
    def tan(self) -> "Vector": ...
    def asin(self) -> "Vector": ...
    def acos(self) -> "Vector": ...
    def atan(self) -> "Vector": ...

    # --- Hyperbolic ---
    def sinh(self) -> "Vector": ...
    def cosh(self) -> "Vector": ...
    def tanh(self) -> "Vector": ...

    # --- Exp/Log ---
    def exp(self) -> "Vector": ...
    def exp2(self) -> "Vector": ...
    def expm1(self) -> "Vector": ...
    def log(self) -> "Vector": ...
    def log2(self) -> "Vector": ...
    def log10(self) -> "Vector": ...
    def log1p(self) -> "Vector": ...

    # --- Reductions ---
    def sum(self) -> float: ...
    def prod(self) -> float: ...
    def mean(self) -> float: ...
    def variance(self) -> float: ...       # sample variance, n>=2
    def std_dev(self) -> float: ...
    def min(self) -> float: ...
    def max(self) -> float: ...

    # --- Predicates ---
    def any(self) -> bool: ...
    def all(self) -> bool: ...
    def isnan(self) -> List[bool]: ...
    def isfinite(self) -> List[bool]: ...
    def isinf(self) -> List[bool]: ...
    def is_integer(self) -> List[bool]: ...
    def is_prime(self) -> List[bool]: ...

    # --- Filtering and selection ---
    def filter_by_mask(self, mask: Union[List[bool], "Vector"]) -> "Vector": ...
    def gt_mask(self, threshold: float) -> "Vector": ...
    def lt_mask(self, threshold: float) -> "Vector": ...
    def eq_mask(self, value: float) -> "Vector": ...
    def filter_gt(self, threshold: float) -> "Vector": ...
    def filter_lt(self, threshold: float) -> "Vector": ...
    def where_(self, mask: List[bool], other: "Vector") -> "Vector": ...

    # --- Sorting and reordering ---
    def sort(self) -> "Vector": ...
    def sort_desc(self) -> "Vector": ...
    def argsort(self) -> List[int]: ...
    def reverse(self) -> "Vector": ...
    def unique(self) -> "Vector": ...

    # --- Cumulative operations ---
    def cumsum(self) -> "Vector": ...
    def cumprod(self) -> "Vector": ...
    def diff(self) -> "Vector": ...

    # --- Shaping / slicing ---
    def head(self, n: int) -> "Vector": ...
    def tail(self, n: int) -> "Vector": ...
    def chunks(self, chunk_size: int) -> List["Vector"]: ...
    def append(self, val: float) -> "Vector": ...
    def extend(self, other: "Vector") -> "Vector": ...

    # --- Elementwise math ---
    def sigmoid(self) -> "Vector": ...
    def clip(self, lo: float, hi: float) -> "Vector": ...
    def hypot_scalar(self, y: float) -> "Vector": ...
    def atan2_scalar(self, x: float) -> "Vector": ...
    def lerp_scalar(self, other: float, t: float) -> "Vector": ...

class ComplexVector:
    """A specialized container for complex-valued (f64 + i*f64) vectors."""
    def __init__(self, real: Sequence[float], imag: Sequence[float]) -> None: ...
    def to_mags(self) -> Vector: ...
    def to_phases(self) -> Vector: ...
    def __len__(self) -> int: ...

# ── Functional API (rmath.vector.*) ──────────────────────────────────────────

def rand(n: int) -> Vector: ...
def randn(n: int) -> Vector: ...
def rand_seeded(n: int, seed: int) -> Vector: ...
def randn_seeded(n: int, seed: int) -> Vector: ...
def arange(start: float, stop: float = ..., step: float = 1.0) -> Vector: ...
def range(start: float, stop: float = ..., step: float = 1.0) -> Vector: ...
def linspace(start: float, stop: float, num: int) -> Vector: ...
def zeros(n: int) -> Vector: ...
def ones(n: int) -> Vector: ...
def full(n: int, val: float) -> Vector: ...
def sum_range(start: float, stop: float = ..., step: float = 1.0) -> float: ...

def sin(v: Vector)  -> Vector: ...
def cos(v: Vector)  -> Vector: ...
def tan(v: Vector)  -> Vector: ...
def asin(v: Vector) -> Vector: ...
def acos(v: Vector) -> Vector: ...
def atan(v: Vector) -> Vector: ...
def sinh(v: Vector) -> Vector: ...
def cosh(v: Vector) -> Vector: ...
def tanh(v: Vector) -> Vector: ...
def exp(v: Vector)  -> Vector: ...
def exp2(v: Vector) -> Vector: ...
def expm1(v: Vector)-> Vector: ...
def log(v: Vector)  -> Vector: ...
def log2(v: Vector) -> Vector: ...
def log10(v: Vector)-> Vector: ...
def log1p(v: Vector)-> Vector: ...
def sqrt(v: Vector) -> Vector: ...
def cbrt(v: Vector) -> Vector: ...
def abs(v: Vector)  -> Vector: ...
def ceil(v: Vector) -> Vector: ...
def floor(v: Vector)-> Vector: ...
def round(v: Vector)-> Vector: ...
def trunc(v: Vector)-> Vector: ...
def fract(v: Vector)-> Vector: ...
def signum(v: Vector)->Vector: ...
def recip(v: Vector)-> Vector: ...

def vsum(v: Vector) -> float: ...
def prod(v: Vector) -> float: ...
def mean(v: Vector) -> float: ...
def variance(v: Vector) -> float: ...
def pop_variance(v: Vector) -> float: ...
def std_dev(v: Vector) -> float: ...
def pop_std_dev(v: Vector) -> float: ...
def median(v: Vector) -> float: ...
def percentile(v: Vector, q: float) -> float: ...
def vmin(v: Vector) -> float: ...
def vmax(v: Vector) -> float: ...
def argmin(v: Vector) -> int: ...
def argmax(v: Vector) -> int: ...
def norm(v: Vector) -> float: ...
def norm_l1(v: Vector) -> float: ...
def norm_inf(v: Vector) -> float: ...
def norm_lp(v: Vector, p: float) -> float: ...
def dot(v1: Vector, v2: Vector) -> float: ...

def add_scalar(v: Vector, s: float) -> Vector: ...
def sub_scalar(v: Vector, s: float) -> Vector: ...
def mul_scalar(v: Vector, s: float) -> Vector: ...
def div_scalar(v: Vector, s: float) -> Vector: ...
def pow_scalar(v: Vector, e: float) -> Vector: ...
def clamp(v: Vector, lo: float, hi: float) -> Vector: ...

def add_vec(v1: Vector, v2: Vector) -> Vector: ...
def sub_vec(v1: Vector, v2: Vector) -> Vector: ...
def mul_vec(v1: Vector, v2: Vector) -> Vector: ...
def div_vec(v1: Vector, v2: Vector) -> Vector: ...

def isnan(v: Vector)     -> List[bool]: ...
def isfinite(v: Vector)  -> List[bool]: ...
def isinf(v: Vector)     -> List[bool]: ...
def is_integer(v: Vector)-> List[bool]: ...
def is_prime(v: Vector)  -> List[bool]: ...
