"""
rmath.geometry — Distance metrics and spatial calculations.
Highly parallelized for long-vector similarity searches.
"""

from typing import List, Tuple, Sequence
from rmath.vector import Vector

class Quaternion:
    """A Quaternion for 3D rotations: q = w + xi + yj + zk."""
    w: float
    x: float
    y: float
    z: float

    def __init__(self, w: float, x: float, y: float, z: float) -> None: ...
    def norm(self) -> float: ...
    def normalize(self) -> 'Quaternion': ...
    def rotate_vector(self, v: Vector) -> Vector: ...
    def __mul__(self, other: 'Quaternion') -> 'Quaternion': ...
    def __repr__(self) -> str: ...

def euclidean_distance(v1: Vector, v2: Vector) -> float: ...
def manhattan_distance(v1: Vector, v2: Vector) -> float: ...
def minkowski_distance(v1: Vector, v2: Vector, p: float) -> float: ...
def cosine_similarity(v1: Vector, v2: Vector) -> float: ...
def projection(v: Vector, target: Vector) -> Vector: ...
def cross_product(v1: Vector, v2: Vector) -> Vector: ...
def angle_between(v1: Vector, v2: Vector) -> float: ...

def is_point_in_polygon(x: float, y: float, poly_x: List[float], poly_y: List[float]) -> bool: ...
def convex_hull(points_x: List[float], points_y: List[float]) -> Tuple[List[float], List[float]]: ...
