"""
rmath.calculus — Automatic Differentiation and Numerical Integration.

Features:
    - Dual: Forward-mode AD using dual numbers (a + bε).
    - Integration: Simpson's and Trapezoidal parallelized rules.
    - Solvers: Newton-Raphson root-finding for exact derivatives.
"""
from typing import Callable, Union, Tuple, Any
from rmath.vector import Vector

class Dual:
    """
    Dual numbers: a + b*epsilon where epsilon^2 = 0.
    Used for Automatic Differentiation (AD).
    """
    val: float
    der: float

    def __init__(self, val: float, der: float) -> None: ...
    @property
    def value(self) -> float: ...
    @property
    def derivative(self) -> float: ...

    def __repr__(self) -> str: ...
    def __add__(self, other: Union['Dual', float]) -> 'Dual': ...
    def __sub__(self, other: Union['Dual', float]) -> 'Dual': ...
    def __mul__(self, other: Union['Dual', float]) -> 'Dual': ...
    def __truediv__(self, other: Union['Dual', float]) -> 'Dual': ...
    def __pow__(self, p: float) -> 'Dual': ...
    def __neg__(self) -> 'Dual': ...

    def sin(self) -> 'Dual': ...
    def cos(self) -> 'Dual': ...
    def exp(self) -> 'Dual': ...
    def log(self) -> 'Dual': ...

def integrate_trapezoidal(x: Vector, y: Vector) -> float: ...
def integrate_simpson_array(y: Vector, dx: float) -> float: ...
def integrate_simpson(f: Callable[[float], float], a: float, b: float, n: int) -> float: ...
def find_root_newton(f: Callable[[Dual], Dual], x0: float, tol: float, max_iter: int) -> float: ...
