from typing import List, Union, Tuple
from .array import Array
from .vector import Vector

def relu(a: Array) -> Array: ...
def sigmoid(a: Array) -> Array: ...
def leaky_relu(a: Array, alpha: float) -> Array: ...
def gelu(a: Array) -> Array: ...
def softmax(a: Array) -> Array: ...
def hardswish(a: Array) -> Array: ...

def mse_loss(a: Array, target: Array) -> float: ...
def cross_entropy_loss(a: Array, labels: List[int]) -> float: ...

def batch_norm(a: Array, mu: Vector, sigma: Vector, gamma: Vector, beta: Vector) -> Array: ...
def layer_norm(a: Array, eps: float) -> Array: ...
def dropout(a: Array, p: float) -> Array: ...

def max_pool2d(a: Array, kernel_size: int) -> Array: ...
def avg_pool2d(a: Array, kernel_size: int) -> Array: ...
