from typing import Tuple, Union, Literal
from rmath.vector import Vector, ComplexVector

def fft(signal: Union[Vector, list[float]]) -> ComplexVector: ...
def ifft(cv: ComplexVector) -> Vector: ...
def fft_styled(signal: Union[Vector, list[float]]) -> Tuple[Vector, Vector]: ...
def rfft(signal: Union[Vector, list[float]]) -> Vector: ...

def convolve(
    signal: Vector,
    kernel: Vector,
    mode: Literal["full", "same", "valid"] = "full"
) -> Vector: ...
